/*:
 * @target MZ
 * @plugindesc Patron rewards: a private hatch on the world map into their own villa, and a habitable world named after each patron out in another galaxy.
 * @author Nocoldiz + Omni-Lex
 *
 * @command report
 * @text Patron Report
 * @desc Prints every registered patron (world square, hatch tile, room, planet) to the console.
 *
 * @command goToHatch
 * @text Go To My Hatch
 * @desc Builds the patron square this savegame knows and sets the party down on the hatch itself. Does nothing where none is known.
 *
 * @help
 * ============================================================================
 * Patron Rewards
 * ============================================================================
 * Every paying patron owns two things in the world:
 *
 *   1. A HATCH on one procedural world square (map 636 at their world
 *      coordinates). The hatch is a Hatch terrain feature stamped by this
 *      plugin after everything else has generated, on exactly the tile their
 *      secret names, in any biome, over whatever was there: a 5x5 yard around
 *      it is wiped of scatter and walls, the ground under it is repaired if
 *      need be and a structure's keep-out region is lifted off it, so the hatch
 *      is always where the record says, is approachable from every side, and
 *      nothing ever grows over it or walls it in. The prefab pass is handed
 *      that yard as keep-out ground before it places anything
 *      (hatchKeepOutRect), so ordinarily there is nothing standing there to
 *      demolish. It cannot be dismantled.
 *      The exception is an alien surface (a GalaxySim landing reuses this map
 *      and world variables 43/44 for its own landing grid), where no hatch is
 *      ever stamped. Going down it opens their VAULT: nine hand-made cellars
 *      stacked under the hatch, Floor -1 (map 664) down to Floor -9, the same
 *      nine in every world and every savegame. They are walked exactly like a
 *      skyscraper's floors, only downwards (ProceduralHouseSystem's descending
 *      fixed stack): the party lands on Floor -1 at 15,18 facing down, each
 *      floor's Downstairs digs one floor deeper, its Upstairs climbs one back
 *      and its Elevator rides to any of them, and the Upstairs on Floor -1
 *      leaves the vault altogether, back onto the hatch tile. Floor -9 is the
 *      bottom and has no Downstairs. The hatch is never locked against its
 *      owner and the tile is the way back out, exactly as for any other door
 *      on the procedural map.
 *      The PatronVault BIOME - the loot cellar's generator on a far bigger
 *      plan, buried in gold and rare weapons - is a separate thing, and is not
 *      behind the hatch: it is the rarest structure an ordinary StairsDown can
 *      open onto
 *      (ProceduralMapStructureGenerator), found by anybody, anywhere. This
 *      plugin still owns what happens inside one: the loot tables
 *      (RandomLootSystem, ContainerSystem), the gold hoards and the weapon
 *      finds are all weighted hard toward the expensive tiers, and a vault dug
 *      under a patron's own square is named after them. A vault hall is a long
 *      walk from its own border, so WorldMapReturn's `exitStructure` plugin
 *      command leaves one from wherever the party is standing and puts them
 *      back on the tile they came in by - the hatch, on a patron's square.
 *   2. A PLANET: a habitable, life-bearing world in a nine-planet system where
 *      no two planets share a type, orbiting an exotic object OUT IN THE MILKY
 *      WAY. They are listed in the star map Catalog under "Patrons", and a
 *      course can be plotted to one like anywhere else in the home galaxy.
 *      The stars are seated on a Vogel spiral keyed on the patron's slot
 *      (starPosition): thousands of light years from each other and from the
 *      Sun, far outside the 130 ly bubble the ordinary catalogue fills, and
 *      unmoved when the patron list grows. They lived in the four Local Group
 *      galaxies until this change.
 *      The object at the centre is either a real exotic class (pulsar,
 *      magnetar, quasi-star, Thorne-Zytkow object and the rest) or one of the
 *      twelve ESOTERIC ones written for this game alone: a black-hole star, a
 *      cursed star, a zombie star, an eyeball star, a five-pointed pentagram
 *      star, an angelic star of concentric wheels of eyes, a star of crude
 *      oil, a clockwork star running down, a mirror star, a bone star, a
 *      hollow star cracked open on nothing, a candle star. The esoteric classes ship
 *      with a frequency of zero in js/db/GalaxySim/StarTypes.json, so a
 *      procedural galaxy never rolls one: the only place in the universe they
 *      burn is over a patron's world. They are built in
 *      GalaxySim_Scene3D_Cosmos (EXOTIC_BUILDERS) like any other exotic star.
 *
 * DATA
 * The patron list is js/db/WorldGen/Patrons.json (window.WorldGen.Patrons),
 * generated by tools/patrons/gen_patrons.js. It holds 480 SLOTS, not just the
 * patrons: the ones past the end of the list are reserved for future patrons,
 * with their square and hatch tile already rolled and encrypted and every
 * other field blank. This plugin filters them out (isClaimed), so a reserved
 * slot has no hatch, no vault, no planet and no catalog entry until
 * somebody's name is put on it in the generator - at which point it turns on
 * exactly where it has been waiting.
 *
 * A patron's coordinates are NOT in it. They would spoil every reward for
 * anybody who opened the file, so each patron carries an encrypted `secret`
 * blob instead, keyed on the coordinates themselves: the game derives the key
 * for whichever world square it is generating anyway, tries the blobs, and a
 * checksum match identifies the owner. Nothing ever decrypts a coordinate it
 * was not already standing on. Reading the coordinates out of the file means
 * deriving a deliberately slow key for all 65,536 squares and testing each -
 * expensive, but a 256x256 world map is only so big: this defeats reading, not
 * a determined cracker. The crypt is mirrored in tools/patrons/patron_crypt.js;
 * change one half and you must change the other.
 *
 * WHERE THE SQUARES ARE
 * Rolled by the generator and spread over the WHOLE world map: it cuts the
 * 256x256 map into cells, takes the cells by farthest-point sampling so no two
 * patrons are neighbours and every corner of the map gets one, and rolls a
 * square inside each. A square is always a field biome (Fields, Meadows,
 * Farm) - open ground on the tileset that declares the Hatch feature - and is
 * never a settlement, a river, a bridge, a town's `reservedTiles` footprint,
 * `base` square or per-direction `coords` square in WorkSystem/Destinations.json
 * (the retired HardcodedBiomeNames.json and NonProceduralCoordinates.json
 * rosters, both folded into that entry), or a square named in
 * HardcodedBiomeOverrides.json.
 * The field biome is a preference, not a condition: the hatch is stamped on
 * the secret's tile whatever biome the square generates as.
 * The hatch tile inside the square is rolled in the ring around the middle of
 * the procedural map, just outside the clearing the party lands in. A named
 * patron's `biome` ships in the clear (it is terrain, not a location) and a
 * reserved slot's does not; the plaintext coordinates live only in
 * docs/patrons-coordinates.md, which is not part of the game build.
 *
 * PUBLIC API
 *   window.PatreonRewards.patrons()                 the table (no coordinates)
 *   window.PatreonRewards.patronAtWorld(x, y)       patron owning a world square
 *   window.PatreonRewards.hatchTileAtWorld(x, y)    their hatch tile on it
 *   window.PatreonRewards.hatchKeepOutRect(x, y)    ground no prefab may take
 *   window.PatreonRewards.applyMapFeatures(mapData, biome, worldCoords)
 *                                                   stamps the hatch (hooked on
 *                                                   DataManager.loadMapData,
 *                                                   after the prefab pass)
 *   window.PatreonRewards.claimSquare(x, y)         the world's own claim, written
 *                                                   when somebody proves the
 *                                                   coordinates; posts the
 *                                                   vessel to every party in it
 *   window.PatreonRewards.claimedSquare()           that claim, or null
 *   window.PatreonRewards.ownHatch()                this savegame's own hatch
 *   window.PatreonRewards.goToOwnHatch()            put the party back on it
 *                                                   (plugin command goToHatch)
 *   window.PatreonRewards.openHatch(tile)           hatch interaction handler
 *   window.PatreonRewards.vaultHouseId()            Floor -1 of the vault
 *   window.PatreonRewards.isInPatronVault()         inside a vault structure?
 *   window.PatreonRewards.vaultPatron()             whose vault it is
 *   window.PatreonRewards.lootRarityBonus()         rarity push for that vault
 *   window.PatreonRewards.starPosition(patron)      their star's seat, in ly
 *   window.PatreonRewards.starDistance(patron)      how far that is from Sol
 *   window.PatreonRewards.ensureSystems(dataManager)
 *   window.PatreonRewards.catalogEntries(dataManager)
 */

(() => {
  "use strict";

  const PLUGIN_NAME = "PatreonRewards";
  const PROC_MAP_ID = 636;

  // ==========================================================================
  // The sealed surface
  // ==========================================================================
  // Switch 199 ("EarthDestroyed"), raised by GalaxySim_Core the day Nibiru
  // strikes - 21 December 2012. A vault outlives the planet it was dug into:
  // the cellars are still there and still reachable from orbit, but the world
  // square over the hatch is not, so there is nothing left to climb out ONTO.
  // From that day Floor -1's Upstairs refuses, and so does the plugin command
  // that puts a party back on their own lid.
  //
  // The random-hatch fallback is deliberately NOT sealed: it is what a broken
  // session uses to get out of a floor it should never have been on, and a
  // party with nowhere to go is worse than a party on a square that is gone.
  const SW_EARTH_LOST = 199;

  function earthGone() {
    try {
      return !!(typeof $gameSwitches !== "undefined" && $gameSwitches && $gameSwitches.value(SW_EARTH_LOST));
    } catch (e) { return false; }
  }

  /** Is there still a surface over the hatch to climb out to? */
  function surfaceSealed() { return earthGone(); }

  /** Say so, once, in the voice the rest of the vault speaks in. */
  function saySealed() {
    if (window.ParchmentToast && window.ParchmentToast.show) {
      window.ParchmentToast.show(T('Patron.vaultSealed'), { severity: 'warning' });
    }
  }

  // ==========================================================================
  // The patrons
  // ==========================================================================
  // js/db/WorldGen/Patrons.json, written by tools/patrons/gen_patrons.js from
  // the Patreon export (paying members only). Each record carries the public
  // half - id, name, tier, planet, star class, galaxy, treasure room - and the
  // encrypted `secret` that holds the world square and hatch tile.
  const DB = (window.WorldGen && window.WorldGen.Patrons) || null;
  const SLOTS = (DB && Array.isArray(DB.patrons)) ? DB.patrons : [];

  // The biome a hatch opens onto: the loot cellar's generator on a much bigger
  // plan, defined in js/db/WorldGen/Biomes.json and laid out by
  // ProceduralMapStructureGenerator (isVault).
  const VAULT_BIOME = "PatronVault";
  // What a patron's hatch actually opens onto: the VAULT, nine hand-made
  // cellars stacked under the hatch tile, Floor -1 down to Floor -9. They are
  // walked exactly like a skyscraper's floors, only downwards
  // (ProceduralHouseSystem's descending fixed stack): each floor carries its
  // own Upstairs, Downstairs and Elevator events, the Upstairs on Floor -1
  // leaving the vault back onto the hatch tile.
  // i18n-ignore-start  map ids
  const VAULT_FLOORS = [664, 666, 662, 660, 659, 668, 655, 647, 1135];

  // The vessel: the one item that carries a party back down to the vault. It is
  // granted per WORLD, not per party - proving the coordinates once is a fact
  // about the world, so every party that world ever raises is handed one,
  // whatever scenario it began in.
  const VESSEL_ITEM_ID = 174;
  // Where the proof is kept: a field of the world's own state file, so it
  // outlives the savegame that proved it and is shared by every savegame of
  // that world (WorldManager, save/worlds/<name>/state.json).
  const WORLD_FILE = "state";        // i18n-ignore  world data file key
  const WORLD_FIELD = "patronVault"; // i18n-ignore  field in it
  // Where the party lands on Floor -1, coming down the hatch.
  const VAULT_ENTRY = { x: 15, y: 18, direction: 2 };
  // i18n-ignore-end

  // Back to the hatch the party came up by, from anywhere: the vault origin's
  // one square, or whichever patron square this savegame last recognised.
  PluginManager.registerCommand(PLUGIN_NAME, "goToHatch", () => {
    goToOwnHatch();
  });

  // A slot with a blank id is RESERVED: its world square and hatch tile are
  // already rolled and encrypted, waiting for the next patron, but it has no
  // name, no vault and no planet yet. Nothing in the game may act on
  // one - it is filtered out here, so no square of it is ever tested, no hatch
  // is ever stamped for it, and it never reaches the star map. Putting a name
  // on it in tools/patrons/gen_patrons.js and rerunning turns it on, at the
  // same coordinates it has been holding all along.
  // specialTreasureRoomId is the generator's claim marker (it is written for
  // every named patron); the hatch no longer leads to a hand-made treasure
  // room, but a slot without one is still a slot nobody has claimed.
  function isClaimed(p) {
    return !!(p && p.id && p.name && p.specialTreasureRoomId);
  }
  const PATRONS = SLOTS.filter(isClaimed);
  // The slot a patron sits in. It is their position in the shipped file, and
  // it is what places their star in the galaxy (starPosition), so appending a
  // patron never moves anybody else's world.
  const SLOT_OF = new Map();
  SLOTS.forEach((p, i) => { if (isClaimed(p)) SLOT_OF.set(p.id, i); });
  const RESERVED = SLOTS.length - PATRONS.length;
  if (!PATRONS.length) {
    console.warn("[PatreonRewards] js/db/WorldGen/Patrons.json is missing or empty: no patron rewards this session");
  }

  // How far the loot tables are pushed toward the expensive tiers inside a
  // patron's vault (RandomLootSystem rarityInfluence points; the whole scale is
  // 0-100, and an ordinary mid-game party sits around 30).
  const LOOT_RARITY_BONUS = 65;
  // Per-tier multiplier applied to ContainerSystem's spawn weights in there,
  // indexed by rarity tier (Common -> Legendary).
  const CONTAINER_TIER_WEIGHTS = [0.1, 0.4, 2, 10, 26];

  // Tiles cleared of scatter around a stamped hatch, in each direction: a
  // 5x5 yard with the hatch in the middle. The hatch tile itself is never
  // negotiable, and neither is room to stand on every side of it - a hatch
  // reachable from one diagonal only is a hatch the party walks past - so the
  // yard is swept of terrain features, prefab walls and keep-out marks alike.
  // Wider than this and every hatch would start eating the buildings around it.
  const HATCH_CLEARANCE = 2;

  // The keep-out square the prefab pass is handed for a patron's own world
  // square (hatchKeepOutRect): the swept yard plus a tile of margin, so a
  // prefab is never even laid over the ground the stamp is about to clear and
  // the yard is not a hole punched through somebody's wall.
  const HATCH_KEEPOUT_MARGIN = 1;

  // The region mark a structure paints over its dead mass. It is lifted inside
  // the yard: a sealed-region map refuses to walk on it, hatch or no hatch.
  const NO_GO_REGION = (window.RegionRules && window.RegionRules.NO_GO_REGION) || 7;

  const log = (...a) => console.log("[PatreonRewards]", ...a);
  const warn = (...a) => console.warn("[PatreonRewards]", ...a);

  // ==========================================================================
  // The coordinate crypt (mirror of tools/patrons/patron_crypt.js)
  // ==========================================================================
  // A patron's square is never stored. Their `secret` is
  //   [worldX, worldY, mapX, mapY, checksum] XOR keystream(kdf(square))
  // so the only way to open it is to already be standing on - or generating -
  // that exact square. Everything below is one key derivation per world square,
  // memoised, plus eight XORs.
  const PEPPER = String((DB && DB.pepper) || "hypernet:patron:hatch:v1");
  const ROUNDS = Number((DB && DB.rounds) || 250000);
  const BLOB_BYTES = 6;

  function mix32(h) {
    h = h >>> 0;
    h ^= h >>> 16;
    h = Math.imul(h, 0x7feb352d) >>> 0;
    h ^= h >>> 15;
    h = Math.imul(h, 0x846ca68b) >>> 0;
    h ^= h >>> 16;
    return h >>> 0;
  }

  function fnv1a(str) {
    let h = 0x811c9dc5 >>> 0;
    const s = String(str);
    for (let i = 0; i < s.length; i++) {
      h ^= s.charCodeAt(i);
      h = Math.imul(h, 0x01000193) >>> 0;
    }
    return h >>> 0;
  }

  const _keyCache = new Map();
  function deriveKey(worldX, worldY) {
    const cacheKey = worldX + "," + worldY;
    const hit = _keyCache.get(cacheKey);
    if (hit !== undefined) return hit;
    let h = fnv1a(PEPPER + ":" + worldX + ":" + worldY);
    for (let i = 0; i < ROUNDS; i++) h = mix32((h + i) >>> 0);
    h = h >>> 0;
    // One entry per square the player has actually visited; a session touches
    // a few hundred at most.
    _keyCache.set(cacheKey, h);
    return h;
  }

  function keystream(key, length) {
    const out = new Array(length);
    let s = key >>> 0;
    for (let i = 0; i < length; i++) {
      s = mix32((s + 0x9e3779b9) >>> 0);
      out[i] = (s >>> 24) & 0xff;
    }
    return out;
  }

  function checksumOf(bytes, key) {
    return fnv1a(PEPPER + "|" + bytes.slice(0, 4).join(",") + "|" + key) & 0xffff;
  }

  function openSecret(hex, key, worldX, worldY) {
    const s = String(hex || "");
    if (s.length !== BLOB_BYTES * 2) return null;
    const bytes = [];
    for (let i = 0; i < s.length; i += 2) bytes.push(parseInt(s.substr(i, 2), 16));
    const ks = keystream(key, BLOB_BYTES);
    const plain = bytes.map((b, i) => (b ^ ks[i]) & 0xff);
    const ck = (plain[4] | (plain[5] << 8)) & 0xffff;
    if (ck !== checksumOf(plain, key)) return null;
    if (plain[0] !== (worldX & 0xff) || plain[1] !== (worldY & 0xff)) return null;
    return { worldX: plain[0], worldY: plain[1], mapX: plain[2], mapY: plain[3] };
  }

  // ==========================================================================
  // Lookups
  // ==========================================================================
  const byId = {};
  for (const p of PATRONS) byId[p.id] = p;

  // Squares already tested: null for "nobody's", { patron, secret } otherwise.
  const _squareCache = new Map();

  /**
   * The patron who owns a world square, and the hatch tile they asked for on
   * it. Returns null for every other square - which is very nearly all of
   * them - and the answer costs one key derivation the first time each square
   * comes up.
   */
  function patronRecordAtWorld(x, y) {
    if (!PATRONS.length) return null;
    if (!Number.isFinite(x) || !Number.isFinite(y)) return null;
    const cacheKey = x + "," + y;
    if (_squareCache.has(cacheKey)) return _squareCache.get(cacheKey);
    const key = deriveKey(x, y);
    let found = null;
    for (const patron of PATRONS) {
      const open = openSecret(patron.secret, key, x, y);
      if (open) { found = { patron, mapCoordinates: [open.mapX, open.mapY] }; break; }
    }
    if (found) rememberHatch(x, y, found);
    _squareCache.set(cacheKey, found);
    return found;
  }

  // ==========================================================================
  // The world's own claim
  // ==========================================================================
  // Typing the coordinates is not something a party does, it is something that
  // happens to a WORLD: the patron proved, once, which square is theirs. The
  // proof is written into the world folder, so a second party raised in that
  // world - any scenario, any savegame - starts knowing where the vault is and
  // is handed the vessel that opens it.
  function claimedSquare() {
    const WM = window.WorldManager;
    if (!WM || typeof WM.getField !== "function") return null;
    if (WM.hasActiveWorld && !WM.hasActiveWorld()) return null;
    try {
      const rec = WM.getField(WORLD_FILE, WORLD_FIELD);
      if (!rec || !Number.isFinite(rec.x) || !Number.isFinite(rec.y)) return null;
      return Object.assign({}, rec);
    } catch (e) {
      return null;
    }
  }

  /**
   * Write the square down as this world's, from the coordinates somebody has
   * just proved they knew. Handed the world square; the hatch tile and the
   * owner are read off the roster, which is the same lookup that proved them.
   * Silently does nothing where no world is active (a playtest straight into a
   * map), leaving the savegame's own record to carry it.
   */
  function claimSquare(worldX, worldY) {
    const rec = patronRecordAtWorld(worldX, worldY);
    if (!rec) return false;
    const WM = window.WorldManager;
    if (!WM || typeof WM.setField !== "function") return false;
    if (WM.hasActiveWorld && !WM.hasActiveWorld()) return false;
    try {
      WM.setField(WORLD_FILE, WORLD_FIELD, {
        id: rec.patron.id, x: worldX, y: worldY,
        mapX: rec.mapCoordinates[0], mapY: rec.mapCoordinates[1],
      });
    } catch (e) {
      return false;
    }
    postVesselToExistingParties(rec.patron);
    // Unlocked on the spot. The party standing there is handed the vessel the
    // moment the coordinates prove out - no scenario has to be chosen, and
    // backing out of the sheet afterwards takes nothing back.
    grantVessel();
    return true;
  }

  /**
   * The parties already living in this world do not reload their character
   * sheet, so they are sent the vessel by POST instead: one parcel each, from
   * the vault itself, with the item enclosed and nothing to pay. Stamped with a
   * key so the same parcel is never delivered twice, whatever reopens this.
   */
  function postVesselToExistingParties(patron) {
    const MS = window.MailSystem;
    const WM = window.WorldManager;
    if (!MS || typeof MS.post !== "function" || typeof MS.partiesIn !== "function") return 0;
    const world = WM && WM.activeWorldName;
    if (!world) return 0;
    const item = $dataItems && $dataItems[VESSEL_ITEM_ID];
    if (!item) return 0;
    let sent = 0;
    for (const card of MS.partiesIn(world)) {
      const res = MS.post({
        world,
        partyId: card.id,
        from: T('Patron.vesselSender'),
        subject: T('Patron.vesselSubject'),
        body: T('Patron.vesselBody', { patron: patron ? patron.name : "" }),
        items: [{ kind: "item", id: VESSEL_ITEM_ID, count: 1 }], // i18n-ignore: item kind
        once: "patronvessel", // i18n-ignore: delivery key
      });
      if (res && res.ok) sent++;
    }
    return sent;
  }

  /**
   * Hand this party the vessel, if the world has a claim and they have none.
   * Idempotent: a party that already carries one (the vault origin's own
   * loadout hands it over on the spot) is not given a second.
   */
  function grantVessel() {
    if (!claimedSquare()) return false;
    if (typeof $gameParty === "undefined" || !$gameParty) return false;
    const item = $dataItems && $dataItems[VESSEL_ITEM_ID];
    if (!item) return false;
    if ($gameParty.numItems(item) > 0) return false;
    $gameParty.gainItem(item, 1);
    return true;
  }

  // Every party that walks a map in a world whose coordinates have been proved
  // is handed the vessel, whatever scenario raised it. Checked on map load
  // rather than at party creation so that a world claimed by a party that
  // already exists reaches the parties already in it too.
  const _Scene_Map_onMapLoaded_vessel = Scene_Map.prototype.onMapLoaded;
  Scene_Map.prototype.onMapLoaded = function () {
    _Scene_Map_onMapLoaded_vessel.call(this);
    try {
      grantVessel();
    } catch (e) {
      warn("the vessel could not be handed over: " + e.message);
    }
  };

  // ==========================================================================
  // Squares the game has already recognised
  // ==========================================================================
  // A square is never stored, only RECOGNISED: the crypt opens a secret with a
  // key derived from the square itself, so there is no way to ask the roster
  // which squares the patrons hold - only to stand on one and be told. That
  // makes "a hatch, any hatch" a question nothing can answer from the file.
  //
  // What CAN be answered is "a hatch this savegame has already met": every
  // square the lookup above opens is written down as it is opened - by the map
  // generator stamping the hatch, by a hatch being used, by the character
  // creation vault origin proving the coordinates it was handed. One is always
  // written down before anybody can be standing inside a vault.
  function knownStore() {
    if (typeof $gameSystem === "undefined" || !$gameSystem) return null;
    if (!Array.isArray($gameSystem._patronKnownHatches)) $gameSystem._patronKnownHatches = [];
    return $gameSystem._patronKnownHatches;
  }

  function rememberHatch(x, y, rec) {
    const store = knownStore();
    if (!store) return;
    if (store.some((h) => h.x === x && h.y === y)) return;
    store.push({ id: rec.patron.id, x: x, y: y, mapX: rec.mapCoordinates[0], mapY: rec.mapCoordinates[1] });
  }

  /** Every patron square this savegame has already recognised. */
  function knownHatches() {
    return (knownStore() || []).map((h) => Object.assign({}, h));
  }

  /** One of them at random, or null while none has been met. */
  function randomKnownHatch() {
    const store = knownStore();
    if (!store || !store.length) return null;
    return Object.assign({}, store[Math.floor(Math.random() * store.length)]);
  }

  /**
   * Climb out of a vault that has no way out recorded - a floor opened from the
   * editor, a debug teleport, a save made before the session existed - by
   * surfacing on a patron hatch: the square is built and the party is set down
   * on the lid itself, exactly where walking out of the vault properly would
   * leave them. Answers false while no patron square has been met, leaving the
   * house system its own fallbacks.
   */
  function surfaceOnRandomHatch() {
    return placeOnHatch(randomKnownHatch());
  }

  /**
   * The hatch this savegame calls its own: the one last stamped (the square the
   * party is standing on, or the one the vault origin proved on its way in),
   * and failing that the first square this game ever recognised. A party that
   * began in a patron's vault has exactly one, so this is that one.
   */
  function ownHatch() {
    if (typeof $gameSystem !== "undefined" && $gameSystem) {
      const last = $gameSystem._patronHatch;
      if (last && Number.isFinite(last.worldX) && Number.isFinite(last.worldY)) {
        return { id: last.id, x: last.worldX, y: last.worldY, mapX: last.x, mapY: last.y };
      }
    }
    const store = knownStore();
    if (store && store.length) return Object.assign({}, store[0]);
    // Nothing in this savegame, but the WORLD may know: a party raised after
    // somebody else proved the coordinates has never met the square itself and
    // still owns the vault. This is what makes the command work for every party
    // of a claimed world, whatever scenario raised it.
    const claimed = claimedSquare();
    if (claimed) return Object.assign({}, claimed);
    return null;
  }

  /**
   * Surface on a named hatch: build its world square and set the party down on
   * the lid, exactly where climbing out of the vault properly would leave them.
   * The one road to a hatch, shared by the random fallback and the plugin
   * command. False where the square cannot be built.
   */
  function surfaceOnHatch(hatch) {
    // The square this hatch is cut into does not exist any more.
    if (surfaceSealed()) { saySealed(); return false; }
    return placeOnHatch(hatch);
  }

  /** The move itself, with no question asked about whether it is allowed. */
  function placeOnHatch(hatch) {
    if (!hatch) return false;
    if (typeof $gameSystem === "undefined" || !$gameSystem.generateOriginBiomeMap) return false;
    const built = $gameSystem.generateOriginBiomeMap({ worldX: hatch.x, worldY: hatch.y });
    if (!built) return false;
    // The two "the procedural map is live" flags, as every arrival onto a built
    // square raises them: without them the square loads with no borders out.
    $gameVariables.setValue(110, 1);
    $gameVariables.setValue(111, 1);
    if (window.WorldMapTransfer) window.WorldMapTransfer.setPlayerWorld(built.worldX, built.worldY);
    // Square-local, like every procedural-map arrival: ProcStitch converts it on
    // the way in and the load settles the party on a tile they can stand on.
    $gamePlayer.reserveTransfer(PROC_MAP_ID, hatch.mapX, hatch.mapY, 2, 0);
    // Called from inside the vault, this IS the way out, so the building
    // session goes with it: left standing, the game still believes the party is
    // nine floors underground.
    const PHS = window.ProceduralHouseSystem;
    if (PHS && typeof PHS.clearHouseSession === "function") PHS.clearHouseSession();
    return true;
  }

  /**
   * The plugin command's own answer: the party's own hatch, with a word to say
   * where they have been put. False, and nothing said, where this savegame has
   * never met a patron square - an ordinary party that never began in a vault.
   */
  function goToOwnHatch() {
    const hatch = ownHatch();
    if (!surfaceOnHatch(hatch)) return false;
    const patron = patronById(hatch.id);
    if (window.ParchmentToast && window.ParchmentToast.show) {
      window.ParchmentToast.show(patron
        ? T('Patron.hatchReturn', { patron: patron.name })
        : T('Patron.hatchReturnUnknown'));
    }
    return true;
  }

  function patronAtWorld(x, y) {
    const rec = patronRecordAtWorld(x, y);
    return rec ? rec.patron : null;
  }

  function patronById(id) {
    return byId[id] || null;
  }

  /**
   * The hatch tile on a world square, as [x, y], or null where no patron owns
   * the square. Costs the one key derivation patronAtWorld costs, and the
   * answer is cached with it. This is the tile the hatch is stamped on, so it
   * is also the tile anything climbing back out of a patron's ground should
   * arrive on (WorldMapReturn's exitStructure).
   */
  /**
   * The tile a record's hatch is actually STAMPED on: the secret's own tile,
   * pulled just inside the map edge if a hand-set coordinate ever pointed at
   * the border. Every place that writes the hatch, looks for it or asks whether
   * the party is standing on it goes through this, so none of them can disagree
   * about a square's lid by a tile.
   */
  function stampedHatchTile(rec) {
    const U = procUtils();
    const width = (U && U.PROC_MAP_WIDTH) || 64;
    const height = (U && U.PROC_MAP_HEIGHT) || 64;
    return [
      Math.max(1, Math.min(width - 2, rec.mapCoordinates[0])),
      Math.max(1, Math.min(height - 3, rec.mapCoordinates[1])),
    ];
  }

  function hatchTileAtWorld(x, y) {
    const rec = patronRecordAtWorld(x, y);
    return rec ? rec.mapCoordinates.slice() : null;
  }

  /**
   * The square on the procedural map that nothing else may build on, for a
   * patron's own world square: the hatch's yard plus a tile of margin, clamped
   * to the map. ProceduralMapPrefabs asks for this before it places anything,
   * so a house is never dropped over a hatch and the yard the stamp sweeps is
   * open ground to begin with rather than a hole through a wall.
   *
   * Null for every square that is not a patron's, and for an alien surface,
   * where no hatch is ever stamped.
   */
  function hatchKeepOutRect(worldX, worldY) {
    if (isAlienSurface(null)) return null;
    const tile = hatchTileAtWorld(worldX, worldY);
    if (!tile) return null;
    const U = procUtils();
    const width = (U && U.PROC_MAP_WIDTH) || 64;
    const height = (U && U.PROC_MAP_HEIGHT) || 64;
    const hx = Math.max(1, Math.min(width - 2, tile[0]));
    const hy = Math.max(1, Math.min(height - 3, tile[1]));
    const reach = HATCH_CLEARANCE + HATCH_KEEPOUT_MARGIN;
    const x0 = Math.max(0, hx - reach);
    const y0 = Math.max(0, hy - reach);
    const x1 = Math.min(width - 1, hx + reach);
    const y1 = Math.min(height - 1, hy + reach);
    return { x: x0, y: y0, width: x1 - x0 + 1, height: y1 - y0 + 1 };
  }

  // ==========================================================================
  // The hatch
  // ==========================================================================
  // Stamped after the whole map is generated (the biome generator calls
  // applyMapFeatures at the very end of generateProceduralTerrain), so nothing
  // that runs during generation can overwrite it. The tiles around it are wiped
  // on the feature layers, leaving nothing but bare terrain: no tree, no rock,
  // no prefab wall can box the hatch in.

  function procUtils() {
    return window.ProcGenUtils || null;
  }

  function biomeFeatures(biome) {
    const U = procUtils();
    if (!U || !U.Cache) return {};
    const tilesetIds = biome.tilesetIds || [biome.tilesetId];
    const all = {};
    for (const tilesetId of tilesetIds) {
      const features = U.Cache.getTilesetFeatures(tilesetId);
      for (const [name, tiles] of Object.entries(features || {})) {
        if (!all[name]) all[name] = [];
        all[name] = all[name].concat(tiles);
      }
    }
    return all;
  }

  function singleTileIds(names, allFeatures) {
    const out = new Set();
    for (const n of names) {
      for (const v of allFeatures[n] || []) {
        if (v && v.type === "single" && v.tileId) out.add(v.tileId);
      }
    }
    return out;
  }

  // Underground layers (a cave or dungeon dug below the square) are not the
  // patron's square: the hatch belongs to the surface only.
  function isUnderground() {
    const pg = (typeof $gameSystem !== "undefined" && $gameSystem) ? $gameSystem._procGenData : null;
    return !!(pg && pg.biomeLayerStack && pg.biomeLayerStack.length > 0);
  }

  /**
   * A structure entered FROM the square is not the square either: a patron's
   * vault, a loot cellar, a temple or a cave den is generated as a top-level
   * map with an empty layer stack (startForcedBiome), so isUnderground() does
   * not catch it, and nothing may stamp a hatch inside one.
   */
  function isStructureBiome(biome) {
    const pg = (typeof $gameSystem !== "undefined" && $gameSystem) ? $gameSystem._procGenData : null;
    const name = String((biome && biome.name) || (pg && pg.currentBiome) || "");
    if (!name) return false;
    // The structure catalogue is the list; the regex below is only the answer
    // for a load order where that plugin is missing.
    const D = window.ProcGenDungeon;
    if (D && typeof D.isDungeonBiome === "function") return D.isDungeonBiome(name);
    return /^(patronvault|lootcellar|templeinside|caveden|dungeon|crypt|sewer)/i.test(name);
  }

  /**
   * A GalaxySim landing, not a square of Earth. Alien surfaces reuse map 636
   * AND world variables 43/44 - those hold the planet's own landing-grid cell
   * while the party is down there - so a grid cell can read as some patron's
   * world square by pure coincidence. No hatch is ever stamped on one.
   */
  function isAlienSurface(biome) {
    if (/^Alien/.test(String((biome && biome.name) || ""))) return true;
    const pg = (typeof $gameSystem !== "undefined" && $gameSystem) ? $gameSystem._procGenData : null;
    if (pg && pg.alienGrid) return true;
    if (pg && /^Alien/.test(String(pg.currentBiome || ""))) return true;
    const GS = window.GalaxySim;
    return !!(GS && typeof GS.isAlienSurface === "function" && GS.isAlienSurface());
  }

  /**
   * Stamp the patron hatch onto a fully built procedural map, if that map is a
   * patron's own world square. Runs after everything else has had its say -
   * terrain, scatter, rivers and prefabs - and lands on THE TILE THE SECRET
   * NAMES, whatever is standing there and whatever biome the square turned out
   * to be. The squares are rolled onto field biomes precisely so that this is
   * almost always open ground, but the stamp does not depend on it: whatever
   * occupies the tile is cleared, the ground under it is made walkable, and the
   * hatch goes down. The party must be able to find it where the record says it
   * is, not a dozen tiles away because a tree grew.
   *
   * The one place it does NOT stamp is an alien surface: those reuse the same
   * map and the same world variables for a planet's landing grid.
   */
  function applyMapFeatures(mapData, biome, worldCoords) {
    if (!mapData || !biome || !worldCoords) return;
    if (isAlienSurface(biome)) return;
    const rec = patronRecordAtWorld(worldCoords.x, worldCoords.y);
    if (!rec) return;
    const patron = rec.patron;
    if (isUnderground() || isStructureBiome(biome)) return;

    const U = procUtils();
    if (!U) return;
    const width = U.PROC_MAP_WIDTH;
    const height = U.PROC_MAP_HEIGHT;
    const idx = (x, y, z) => z * width * height + y * width + x;

    const allFeatures = biomeFeatures(biome);
    const hatch = (allFeatures["Hatch"] || []).find((v) => v && v.type === "single" && v.tileId); // i18n-ignore: Features.json id
    if (!hatch) {
      warn(`tileset ${biome.tilesetId} declares no single-tile Hatch: ${patron.name}'s hatch not placed`);
      return;
    }

    // The tile the secret names, as every other answer here reads it.
    const [hx, hy] = stampedHatchTile(rec);

    // Already stamped: this map array was built earlier in the session and is
    // being re-entered.
    if (mapData[idx(hx, hy, 2)] === hatch.tileId) {
      recordHatch(patron, worldCoords, hx, hy);
      return;
    }

    const blocked = singleTileIds(
      ["Water", "Ocean", "Beach", "Lava", "Magma"], allFeatures); // i18n-ignore: Features.json ids
    const walkable = (x, y) => {
      const base = mapData[idx(x, y, 0)];
      return base > 0 && !blocked.has(base);
    };
    // The commonest walkable ground on this map, used to fill in under the
    // hatch when the rolled tile turned out to be water, lava or a hole. Nine
    // times in ten there is nothing to fill: the square is a field.
    const groundTile = () => {
      const tally = new Map();
      for (let y = 1; y < height - 1; y++) {
        for (let x = 1; x < width - 1; x++) {
          if (!walkable(x, y)) continue;
          const t = mapData[idx(x, y, 0)];
          tally.set(t, (tally.get(t) || 0) + 1);
        }
      }
      let best = 0;
      let bestCount = 0;
      for (const [t, n] of tally) if (n > bestCount) { best = t; bestCount = n; }
      return best;
    };

    // Clear the hatch tile and the yard around it on every feature layer -
    // scatter, walls, whatever a prefab put there - so the hatch is never boxed
    // in and is always approachable from any side, repair any ground that will
    // not carry a walker, and lift the keep-out region a structure may have
    // painted over the mass. Deliberately a small box: this overrides what is
    // there, and the less of somebody else's building it takes with it the
    // better. The prefab pass is asked to leave this square alone up front
    // (hatchKeepOutRect), so ordinarily there is nothing here to demolish.
    let fill = 0;
    for (let dy = -HATCH_CLEARANCE; dy <= HATCH_CLEARANCE; dy++) {
      for (let dx = -HATCH_CLEARANCE; dx <= HATCH_CLEARANCE; dx++) {
        const x = hx + dx;
        const y = hy + dy;
        if (x < 0 || y < 0 || x >= width || y >= height) continue;
        for (const z of [1, 2, 3]) mapData[idx(x, y, z)] = 0;
        if (!walkable(x, y)) {
          if (!fill) fill = groundTile();
          if (fill) mapData[idx(x, y, 0)] = fill;
        }
        const region = idx(x, y, 5);
        if (region < mapData.length && mapData[region] === NO_GO_REGION) {
          mapData[region] = 0;
        }
      }
    }
    mapData[idx(hx, hy, 2)] = hatch.tileId;
    recordHatch(patron, worldCoords, hx, hy);
  }

  function recordHatch(patron, worldCoords, x, y) {
    if (typeof $gameSystem === "undefined" || !$gameSystem) return;
    $gameSystem._patronHatch = {
      id: patron.id, worldX: worldCoords.x, worldY: worldCoords.y, x, y,
    };
  }

  // The stamp runs at map-load time, AFTER ProceduralMapPrefabs has applied its
  // prefabs to the generated array (that plugin hooks the same call and this one
  // loads later, so this wrapper's tail runs last). Stamping during generation
  // instead would let a prefab house be dropped on top of the hatch.
  const _DataManager_loadMapData = DataManager.loadMapData;
  DataManager.loadMapData = function (mapId) {
    _DataManager_loadMapData.call(this, mapId);
    if (mapId !== PROC_MAP_ID || !PATRONS.length) return;
    const pg = $gameSystem && $gameSystem._procGenData;
    if (!pg || !pg.generatedMapData || !$dataMap) return;
    // Variables 43/44 mean something else entirely while the party is on an
    // alien surface, so nothing below may even look at them.
    if (isAlienSurface(null)) return;
    // WHICH SQUARE THIS IS: the procgen data's own answer first, the world
    // variables only as a fallback. They disagree for one frame on exactly the
    // route that matters - climbing out of the vault, where the square is
    // restored before the variables catch up - and reading the variables there
    // meant the square loaded with no hatch on it until something else (a
    // battle, a menu) reloaded the map and asked again.
    const worldCoords = currentWorldCoords() || {
      x: $gameVariables.value(43) || 0,
      y: $gameVariables.value(44) || 0,
    };
    if (!patronRecordAtWorld(worldCoords.x, worldCoords.y)) return;
    const biome = biomeByName(pg.currentBiome);
    if (!biome) return;
    try {
      applyMapFeatures(pg.generatedMapData, biome, worldCoords);
      // The procedural map may be a stitched window of several squares, which
      // holds a COPY of this square's tiles: the hatch has to be blitted back
      // into it or it would be stamped on an array nobody is looking at.
      if (window.ProcStitch && window.ProcStitch.active()) {
        window.ProcStitch.syncCell(worldCoords.x, worldCoords.y);
      }
    } catch (e) {
      warn("hatch stamping failed: " + e.message);
    }
  };

  /**
   * The same stamp, on the LIVE map, once the scene has it. Everything that
   * rebuilds or re-injects this square - WorldMapReturn putting the saved tiles
   * back, ProcStitch blitting a stitched window, a structure restoring the
   * surface behind it - writes into $dataMap.data AFTER DataManager.loadMapData
   * has run, and any one of them can lay the square back down without the lid.
   * So the hatch is asserted here as well, where nothing runs after it: cheap
   * (one tile read on a patron square, nothing at all anywhere else) and the
   * only way the hatch is on the map the party is actually walking on.
   */
  function stampLiveMap() {
    if (typeof $gameMap === "undefined" || !$gameMap || $gameMap.mapId() !== PROC_MAP_ID) return;
    if (!$dataMap || !$dataMap.data || !PATRONS.length) return;
    if (isAlienSurface(null) || isUnderground()) return;
    const here = currentWorldCoords();
    if (!here) return;
    const rec = patronRecordAtWorld(here.x, here.y);
    if (!rec) return;
    const pg = $gameSystem && $gameSystem._procGenData;
    const biome = pg ? biomeByName(pg.currentBiome) : null;
    if (!biome || isStructureBiome(biome)) return;
    const hatch = (biomeFeatures(biome)["Hatch"] || [])   // i18n-ignore: Features.json id
      .find((v) => v && v.type === "single" && v.tileId);
    if (!hatch) return;
    // The square is always stamped in ITS OWN array, which is a plain 64x64
    // square whatever the scene is showing. $dataMap is only written directly
    // when it IS that square: a stitched window is a bigger map holding a copy
    // of several, and ProcStitch is the one thing that knows how to put a cell
    // back into it.
    const U = procUtils();
    const w = (U && U.PROC_MAP_WIDTH) || 64;
    const h = (U && U.PROC_MAP_HEIGHT) || 64;
    const [hx, hy] = stampedHatchTile(rec);
    const stitch = window.ProcStitch && window.ProcStitch.active && window.ProcStitch.active();
    if (pg && pg.generatedMapData) {
      applyMapFeatures(pg.generatedMapData, biome, here);
    }
    if (stitch) {
      window.ProcStitch.syncCell(here.x, here.y);
    } else if ($dataMap.width === w && $dataMap.height === h) {
      if ($dataMap.data[2 * w * h + hy * w + hx] === hatch.tileId) return;
      applyMapFeatures($dataMap.data, biome, here);
    }
    if ($gameMap.requestRefresh) $gameMap.requestRefresh();
  }

  /**
   * Every patron square standing in a stitched window gets its lid, not just
   * the one the window was opened around. A window is several squares laid side
   * by side and grown as the party walks: a square joined on at the edge was
   * built by the square API and laid down without this plugin ever seeing a map
   * load, so its hatch would be missing until something reloaded the whole map.
   * Each cell carries its own array, which is the array the stamp belongs in;
   * syncCell blits it back into the window.
   */
  function stampWindowCells() {
    const stitch = window.ProcStitch;
    if (!stitch || !stitch.active || !stitch.active()) return;
    if (typeof stitch.window !== "function" || typeof stitch.syncCell !== "function") return;
    const win = stitch.window();
    if (!win || !Array.isArray(win.cells)) return;
    for (const cell of win.cells) {
      const built = cell && cell.built;
      if (!built || !built.mapData) continue;
      if (!patronRecordAtWorld(cell.worldX, cell.worldY)) continue;
      const name = built.resolved && built.resolved.biomeName;
      const biome = name ? biomeByName(name) : null;
      if (!biome || isStructureBiome(biome)) continue;
      applyMapFeatures(built.mapData, biome, { x: cell.worldX, y: cell.worldY });
      stitch.syncCell(cell.worldX, cell.worldY);
    }
  }

  const _Scene_Map_onMapLoaded_hatch = Scene_Map.prototype.onMapLoaded;
  Scene_Map.prototype.onMapLoaded = function () {
    _Scene_Map_onMapLoaded_hatch.call(this);
    try {
      populateVaultFloor();
    } catch (e) {
      warn("the vault's residents could not be put on the floor: " + e.message);
    }
    try {
      stampLiveMap();
      stampWindowCells();
    } catch (e) {
      warn("the hatch could not be asserted on the live map: " + e.message);
    }
  };

  // ... and again whenever the party sets foot in a different square without a
  // transfer, which is how a window's far cells are reached.
  if (window.ProcStitch && typeof window.ProcStitch.onSquareChanged === "function") {
    window.ProcStitch.onSquareChanged(() => {
      try {
        stampWindowCells();
      } catch (e) {
        warn("the hatch could not be asserted on the square walked into: " + e.message);
      }
    });
  }

  function biomeByName(name) {
    const list = (window.WorldGen && window.WorldGen.Biomes) || [];
    return list.find((b) => b && b.name === name) || null;
  }

  /** The world square the procedural map currently shows. */
  function currentWorldCoords() {
    const pg = (typeof $gameSystem !== "undefined" && $gameSystem) ? $gameSystem._procGenData : null;
    if (!pg) return null;
    const x = pg.originX != null ? pg.originX : (pg.worldX != null ? pg.worldX : $gameVariables.value(43));
    const y = pg.originY != null ? pg.originY : (pg.worldY != null ? pg.worldY : $gameVariables.value(44));
    return { x, y };
  }

  /**
   * A MAP coordinate on the procedural map, resolved into the world square it
   * stands on and its position inside that square. The two are the same thing
   * only when one square is loaded on its own: a stitched window is a single
   * map holding several squares side by side, so the party can be walking
   * around at map coordinate 84,21 while the hatch's secret says 20,21 of the
   * square next door. Everything that compares a tile against a secret has to
   * come through here, or a hatch in a window is a tile nothing answers for.
   */
  function squareOfMapTile(tile) {
    const stitch = window.ProcStitch;
    if (stitch && stitch.active && stitch.active() &&
        typeof stitch.squareAt === "function" && typeof stitch.local === "function") {
      const world = stitch.squareAt(tile.x, tile.y);
      const local = stitch.local(tile.x, tile.y);
      if (world && local) return { world, local };
    }
    const here = currentWorldCoords();
    return here ? { world: here, local: { x: tile.x, y: tile.y } } : null;
  }

  /** The patron whose hatch sits on (tile.x, tile.y) of the current map. */
  function patronOfHatchTile(tile) {
    if (typeof $gameMap === "undefined" || !$gameMap || $gameMap.mapId() !== PROC_MAP_ID) return null;
    if (isAlienSurface(null)) return null;
    const pg = $gameSystem && $gameSystem._procGenData;
    const at = squareOfMapTile(tile);
    if (!pg || !at) return null;
    const here = at.world;
    // The SECRET is the authority on where this square's hatch is, not the
    // note the stamp left on $gameSystem: that note is one square's worth of
    // bookkeeping and can be left over from another square entirely (the vault
    // origin writes it before the party has stood anywhere), and a hatch that
    // does not answer to the tile it is stamped on is a hatch the party walks
    // over for good.
    const rec = patronRecordAtWorld(here.x, here.y);
    if (!rec) return null;
    const [hx, hy] = stampedHatchTile(rec);
    if (hx !== at.local.x || hy !== at.local.y) return null;
    return rec.patron;
  }

  /**
   * Which villa a patron's hatch opens onto. The pick is seeded on the world
   * SQUARE alone - not on the world seed, not on the map or the tile - so a
   * patron owns the same one of the eight villa interiors in every world, in
   * every savegame, forever.
   */
  function vaultHouseId() {
    return VAULT_FLOORS[0];
  }

  /**
   * Hatch interaction: the patron's vault, the same nine cellars on every visit
   * and in every world. ProceduralHouseSystem owns the entry, so the hatch tile
   * is the return point exactly as it is for every other door on the procedural
   * map, and the hatch is never locked against its owner. Called by
   * ProceduralTerrainInteractions' Hatch handler. Never dismantles anything.
   */
  function openHatch(tile) {
    const patron = patronOfHatchTile(tile);
    if (!patron) return false;
    // Finding the lid IS the proof. Typing the coordinates at creation was
    // never meant to be the only way in: a party that walks onto a patron's
    // hatch has stood on the square, which is the same fact the crypt asks for,
    // so the world is claimed here as well and the vessel goes out with it.
    const at = squareOfMapTile(tile);
    if (at) claimSquare(at.world.x, at.world.y);
    const PHS = window.ProceduralHouseSystem;
    if (!PHS || typeof PHS.enterTileStackAt !== "function") {
      warn("ProceduralHouseSystem is missing: the hatch cannot open");
      return false;
    }
    if (!PHS.enterTileStackAt(tile.x, tile.y, VAULT_FLOORS, {
      descending: true,
      x: VAULT_ENTRY.x, y: VAULT_ENTRY.y, direction: VAULT_ENTRY.direction,
    })) return false;
    AudioManager.playSe({ name: "Door1", volume: 90, pitch: 100, pan: 0 });
    return true;
  }

  // Stepping onto the lid opens it. ProceduralTerrainInteractions already
  // walks the party into every other structure entrance, but it refuses on a
  // handful of conditions of its own (a dungeon session left on the procgen
  // data, a layer stack, its own step lock) and the hatch is the one entrance
  // that must never be walked over: it is the only way into a vault, it is
  // stamped after generation, and a party standing on their own lid trying to
  // get in is not in a position to guess why nothing happened. So the step is
  // answered here as well, off the player's own step, and the two routes cannot
  // both fire because opening transfers the party off the tile.
  let _hatchStepLock = 0;

  function tryHatchUnderfoot() {
    if (typeof $gamePlayer === "undefined" || !$gamePlayer) return false;
    if (Graphics.frameCount < _hatchStepLock) return false;
    if ($gamePlayer.isInVehicle()) return false;
    if ($gameMap && $gameMap.isEventRunning()) return false;
    if ($gameMessage && $gameMessage.isBusy && $gameMessage.isBusy()) return false;
    // A real event standing on the tile speaks for itself, exactly as the
    // terrain interactions let it.
    if ($gameMap && $gameMap.events().some((e) => e && e.x === $gamePlayer.x && e.y === $gamePlayer.y)) {
      return false;
    }
    if (!patronOfHatchTile({ x: $gamePlayer.x, y: $gamePlayer.y })) return false;
    if (!openHatch({ x: $gamePlayer.x, y: $gamePlayer.y })) return false;
    _hatchStepLock = Graphics.frameCount + 60;
    return true;
  }

  const _Game_Player_increaseSteps_hatch = Game_Player.prototype.increaseSteps;
  Game_Player.prototype.increaseSteps = function () {
    _Game_Player_increaseSteps_hatch.call(this);
    try {
      tryHatchUnderfoot();
    } catch (e) {
      warn("the hatch underfoot could not open: " + e.message);
    }
  };

  // ==========================================================================
  // Who lives down there
  // ==========================================================================
  // An unlocked vault is not nine empty cellars: it is where the world's idle
  // companions ended up. Everybody this world ever recorded as having left a
  // party and joined no other - the retired, the dismissed, the ones a
  // savegame walked away from - is somewhere on the nine floors, living the
  // ordinary NPC life every other person in the world lives (NPCSystem's brain
  // and society profile, so they roam, they talk, they can be empathized with
  // and they turn up in the wiki), in the equipment they left in.
  //
  // Which floor is a pure function of the name, so a companion is always on
  // the same floor of the same vault, and they are spread evenly over the nine
  // rather than crowding the one the party arrives on.

  // Which floor somebody is on is no longer a fact about their name. A vault
  // resident is somewhere in the vault, and where in it is rolled again on
  // every descent, so nine floors are nine chances of running into them
  // instead of one step they are always standing on.
  function randomVaultFloor() {
    return Math.floor(Math.random() * VAULT_FLOORS.length);
  }

  // A tile on this floor somebody can stand on, picked by name so they are
  // always in the same corner of it. Scans the floor for standable, unoccupied
  // ground rather than guessing at coordinates: the nine cellars are
  // hand-drawn and no two are laid out alike.
  function vaultSpotForName(name) {
    if (!$gameMap) return null;
    const free = [];
    for (let y = 0; y < $gameMap.height(); y++) {
      for (let x = 0; x < $gameMap.width(); x++) {
        if (!$gameMap.isPassable(x, y, 2)) continue;
        if ($gameMap.eventsXy(x, y).length) continue;
        if ($gamePlayer && $gamePlayer.x === x && $gamePlayer.y === y) continue;
        free.push({ x, y });
      }
    }
    if (!free.length) return null;
    let seed = 7;
    for (const ch of String(name || "")) seed = ((seed * 33) + ch.charCodeAt(0)) >>> 0;
    return free[seed % free.length];
  }

  /**
   * Put this floor's share of the vault's residents on it. Answers how many
   * were newly spawned; does nothing at all outside a vault, or in a world
   * whose coordinates nobody has proved.
   *
   * WHO lives down here is the Dynamics board's business, not this plugin's:
   * an idle companion is assigned to the vault there, the same way they are
   * assigned to a house or to the ship, and window.PartyLodging is the one
   * answer to where anybody lives. This is only the floor they are put on.
   */
  function populateVaultFloor() {
    if (typeof $gameMap === "undefined" || !$gameMap) return 0;
    const floor = VAULT_FLOORS.indexOf($gameMap.mapId());
    if (floor < 0) return 0;
    // Locked, and nobody is down there: the vault is not part of this world yet.
    if (!claimedSquare()) return 0;
    const LG = window.PartyLodging;
    const VP = window.PartyPresence;
    if (!LG || typeof LG.residents !== "function") return 0;
    if (!VP || typeof VP.spawnOne !== "function") return 0;
    if (!$dataMap) return 0;
    if (!$dataMap.events) $dataMap.events = [null];
    let spawned = 0;
    for (const member of LG.residents()) {
      if (member.lodging !== "vault") continue;   // i18n-ignore: place id
      if (randomVaultFloor() !== floor) continue;
      const key = "vaultresident:" + member.name;  // i18n-ignore: event key
      if (VP.findEvent && VP.findEvent(key)) continue;
      const spot = vaultSpotForName(member.name);
      if (!spot) continue;
      const person = {
        key,
        name: member.name,
        characterName: member.characterName || "",
        characterIndex: member.characterIndex || 0,
        classId: member.classId,
        level: member.level,
      };
      // spawnOne reads the party's recorded location for somewhere to stand;
      // down here that is the tile picked above, and it is on this floor.
      if (!VP.spawnOne(person, { slot: null, location: { x: spot.x, y: spot.y } })) continue;
      spawned++;
      // They are still in what they left in, and the profile is where anything
      // that inspects them (the Empathize panel, the wiki) reads it from.
      try {
        const profile = window.NPCSocietyRegistry && window.NPCSocietyRegistry.getProfile
          ? window.NPCSocietyRegistry.getProfile(member.name) : null;
        if (profile && Array.isArray(member.equips)) profile.equipment = member.equips.slice();
      } catch (e) { /* the resident stands there dressed either way */ }
    }
    return spawned;
  }

  // ==========================================================================
  // Inside a patron's vault
  // ==========================================================================
  // A vault only ever reachable through one hatch, in one square of one world,
  // pays out accordingly: RandomLootSystem weights toward the expensive tiers
  // and ContainerSystem's own rarity weights are re-scaled the same way. The
  // gold hoards and weapon finds scattered over its floor are lifted by
  // ProceduralTerrainInteractions, which asks isInPatronVault() as well.
  function isInPatronVault() {
    if (typeof $gameMap === "undefined" || !$gameMap) return false;
    if ($gameMap.mapId() !== PROC_MAP_ID) return false;
    const pg = (typeof $gameSystem !== "undefined" && $gameSystem) ? $gameSystem._procGenData : null;
    return !!(pg && pg.currentBiome === VAULT_BIOME);
  }

  /**
   * The patron whose vault the party is in. A vault is no longer entered
   * through a hatch: it is a rare structure dealt to ordinary stairways, so it
   * belongs to a patron only when it happens to have been dug under that
   * patron's own world square. Anywhere else it is nobody's and keeps the
   * biome's own name.
   */
  function vaultPatron() {
    if (!isInPatronVault()) return null;
    const here = currentWorldCoords();
    return here ? patronAtWorld(here.x, here.y) : null;
  }

  /**
   * Whose vault this is, standing at the top of it. The floors are hand-made
   * maps shared by every patron, so the owner is not written on the map: it is
   * whoever's lid was opened to get here (the note the stamp leaves, which is
   * exactly one square's worth of bookkeeping and is right for as long as the
   * party is under that square), and failing that the square this world has had
   * proved to it. Null in a world nobody has claimed - the floors keep their
   * authored names there.
   *
   * Only FLOOR -1 is renamed. It is the one the party arrives on, so it is
   * where the name belongs; every floor under it says how deep it is instead,
   * which is what is worth knowing down there.
   */
  function vaultFloorPatron() {
    if (typeof $gameMap === "undefined" || !$gameMap) return null;
    if ($gameMap.mapId() !== VAULT_FLOORS[0]) return null;
    const hatch = ownHatch();
    if (!hatch) return null;
    return patronById(hatch.id) || (Number.isFinite(hatch.x)
      ? patronAtWorld(hatch.x, hatch.y) : null);
  }

  function lootRarityBonus() {
    return isInPatronVault() ? LOOT_RARITY_BONUS : 0;
  }

  function containerTierWeight(tierIndex) {
    if (!isInPatronVault()) return 1;
    const i = Math.max(0, Math.min(CONTAINER_TIER_WEIGHTS.length - 1, tierIndex));
    return CONTAINER_TIER_WEIGHTS[i];
  }

  // The map name banner: a patron's vault is announced as theirs instead of by
  // its biome name. Wraps whatever MapLevelDisplay has already put on
  // Game_Map (this plugin loads after it), so the level suffix is dropped here
  // on purpose - the vault is named, not rated.
  const _Game_Map_displayName = Game_Map.prototype.displayName;
  Game_Map.prototype.displayName = function () {
    const patron = vaultPatron() || vaultFloorPatron();
    if (patron) return T('Patron.vaultName', { patron: patron.name });
    return _Game_Map_displayName.call(this);
  };

  // ==========================================================================
  // The planets
  // ==========================================================================
  // Each patron gets one star system OUT IN THE MILKY WAY: an exotic object
  // with nine planets, no two of the same type, one of them their own
  // habitable, life-bearing world, and moons scattered over the rest.
  //
  // They used to live in the four Local Group galaxies, which put them a
  // galaxy-hop away and hid them behind a scale the player rarely visits. They
  // are in the home galaxy now, registered under a plain "PATRON.<id>" name -
  // deliberately NOT the "GX.<seed>.<i>" shape, which the rest of the star map
  // reads as "belongs to another galaxy" - so they are ordinary members of
  // this galaxy's system list and the whole map (picking, travel, save and
  // restore) treats them as natives with no special cases.
  //
  // They are still nowhere near each other. Their positions are a Vogel
  // spiral over the disk keyed on the SLOT, so every patron is thousands of
  // light years from the next one and from the Sun, and a new patron lands in
  // the next empty seat of the spiral without moving anybody.

  // Planet types the nine-planet spread is drawn from: everything with a real
  // surface or envelope, no asteroids or comets (those belong in belts).
  const PLANET_POOL = [
    "sub_mercurian", "mercurian", "sub_earth", "super_earth", "mini_neptune",
    "ice", "ocean", "lava_ocean", "desert", "rainforest", "tundra",
    "acid_ocean", "gas_giant", "hot_jupiter", "cold_jupiter", "ice_giant",
    "ringed_gas_giant", "puffy", "chthonian", "mega_iron", "carbon",
    "diamond", "magma_planet", "earth_like",
  ];
  // Bodies that can sensibly hang in orbit around a planet.
  const MOON_POOL = [
    "sub_mercurian", "mercurian", "ice", "desert", "tundra", "dwarf",
    "planetesimal", "sub_earth", "magma_planet", "carbon",
  ];
  const PATRON_PLANET_TYPE = "habitable";

  function GS() { return window.GalaxySim || null; }

  function systemNameFor(patron) {
    return "PATRON." + patron.id;
  }

  // --- Where a patron's star stands in the Milky Way -------------------------
  // A Vogel (sunflower) spiral: slot n sits at radius SPIRAL_STEP*sqrt(n+0.5)
  // and angle n*GOLDEN_ANGLE, in light years from the Sun on the disk plane.
  // It depends on the slot and nothing else, which is what keeps a patron's
  // star where it was when the list grows, and it spaces the seats evenly:
  // consecutive slots are never neighbours and no two seats are closer than
  // about SPIRAL_STEP apart. 700 ly a seat puts the whole 480-slot spiral
  // inside a 15,300 ly circle - a good way out into the arm, comfortably
  // inside the disk in every direction, and far outside the 130 ly bubble the
  // ordinary catalogue fills.
  const GOLDEN_ANGLE = Math.PI * (3 - Math.sqrt(5));
  const SPIRAL_STEP = 700;          // light years between neighbouring seats
  const DISK_HALF_HEIGHT = 220;     // thin-disk scatter, light years

  function starPosition(patron) {
    const slot = SLOT_OF.has(patron.id) ? SLOT_OF.get(patron.id) : 0;
    const r = SPIRAL_STEP * Math.sqrt(slot + 0.5);
    const a = slot * GOLDEN_ANGLE;
    // The height off the plane is the only part that is rolled, and it is
    // rolled from the id so it never depends on the load order.
    let h = 2166136261 >>> 0;
    const s = String(patron.id);
    for (let i = 0; i < s.length; i++) {
      h ^= s.charCodeAt(i);
      h = Math.imul(h, 16777619) >>> 0;
    }
    const z = (((h >>> 8) % 2001) / 1000 - 1) * DISK_HALF_HEIGHT;
    return { x: r * Math.cos(a), y: r * Math.sin(a), z };
  }

  /** How far a patron's star is from Sol, in light years. */
  function starDistance(patron) {
    const p = starPosition(patron);
    return Math.sqrt(p.x * p.x + p.y * p.y + p.z * p.z);
  }

  function buildPatronSystem(patron, dataManager) {
    const G = GS();
    if (!G || !G.Math || !G.StarTypes || !G.PlanetTypes) return null;
    const RandomGenerator = G.Math.RandomGenerator;
    const STAR_COLORS = G.Math.STAR_COLORS || {};
    const PLANET_COLORS = G.Math.PLANET_COLORS || {};
    const STAR_TYPES = G.StarTypes;
    const PLANET_TYPES = G.PlanetTypes;

    const rng = new RandomGenerator("PATRON:" + patron.id);

    const starType = STAR_TYPES[patron.starType] ? patron.starType : "PULSAR";
    const sd = STAR_TYPES[starType];
    const mass = rng.range(sd.mass[0], sd.mass[1]);
    const radius = rng.range(sd.radius[0], sd.radius[1]);
    // Orbital periods are Keplerian in the star's mass, and some of these
    // objects are monsters (a quasi-star runs to millions of solar masses),
    // which spun their planets round the star fast enough to strobe. The orbits
    // are drawn from a capped mass so a patron's system reads like a system:
    // physically a lie, but the alternative is unwatchable.
    const orbitMass = Math.max(0.5, Math.min(mass, 4));

    // Its seat in the spiral: light years from Sol on the disk plane, with a
    // little height off it. Nothing here is rolled (see starPosition).
    const where = starPosition(patron);
    const system = {
      name: systemNameFor(patron),
      label: T('Patron.starLabel', { planet: patron.planetName }),
      patron: { id: patron.id, name: patron.name },
      type: starType,
      color: STAR_COLORS[starType] || "#ffffff",
      // x/y are the disk plane and z the height off it, exactly as every
      // other system in this galaxy is laid out (generateProceduralSystems).
      position: { x: where.x, y: where.y, z: where.z },
      mass,
      radius,
      temperature: rng.range(sd.temp[0], sd.temp[1]),
      luminosity: dataManager && dataManager.calculateLuminosity
        ? dataManager.calculateLuminosity({ mass, radius })
        : Math.pow(mass, 3.5) * Math.pow(radius, 2) * 0.001,
      binary: false,
      hardcoded: false,
      planets: [],
    };

    // Nine planets, every one a different type, with the patron's own world
    // dropped into a middle orbit where a habitable world belongs.
    const pool = PLANET_POOL.slice();
    for (let i = pool.length - 1; i > 0; i--) {
      const j = rng.int(0, i);
      const t = pool[i]; pool[i] = pool[j]; pool[j] = t;
    }
    const types = pool.slice(0, 8);
    const patronSlot = 2 + rng.int(0, 2);
    types.splice(patronSlot, 0, PATRON_PLANET_TYPE);

    let orbit = 0.25 + rng.random() * 0.2;
    types.forEach((type, index) => {
      const pd = PLANET_TYPES[type] || { minMass: 0.1, maxMass: 5 };
      const isPatronWorld = index === patronSlot;
      const planet = {
        name: isPatronWorld
          ? patron.planetName
          : patron.planetName + " " + String.fromCharCode(98 + index),
        type,
        color: PLANET_COLORS[type] || "#888888",
        orbitRadius: Number(orbit.toFixed(3)),
        radius: isPatronWorld ? rng.range(0.9, 1.3) : rng.range(0.4, 3),
        mass: rng.range(pd.minMass, pd.maxMass),
        period: Math.sqrt(Math.pow(orbit, 3) / orbitMass) * 365,
        phase: rng.random() * Math.PI * 2,
        atmosphere: isPatronWorld ? true : rng.random() < 0.5,
        // Read by GalaxySim.planetHasLife: authored life, not a rolled chance.
        life: isPatronWorld || undefined,
        note: isPatronWorld
          ? T('Patron.surveyNote', { patron: patron.name })
          : null,
        moons: [],
      };

      // Moons: a couple each on average, and never none on the patron's world.
      const moonCount = isPatronWorld ? 1 + rng.int(0, 2) : rng.int(0, 3);
      const planetMassInSolar = planet.mass / 333000.0;
      let moonOrbit = 0.002 + rng.random() * 0.004;
      for (let m = 0; m < moonCount; m++) {
        const mt = MOON_POOL[rng.int(0, MOON_POOL.length - 1)];
        const md = PLANET_TYPES[mt] || { minMass: 0.001, maxMass: 0.1 };
        planet.moons.push({
          name: planet.name + " " + String.fromCharCode(97 + m),
          type: mt,
          color: PLANET_COLORS[mt] || "#888888",
          orbitRadius: Number(moonOrbit.toFixed(4)),
          radius: rng.range(0.1, 0.45),
          mass: rng.range(md.minMass, md.maxMass) * 0.05,
          period: Math.sqrt(Math.pow(moonOrbit, 3) / (planetMassInSolar || 1e-6)) * 365,
          phase: rng.random() * Math.PI * 2,
          atmosphere: false,
          note: null,
        });
        moonOrbit *= 1.6 + rng.random();
      }

      system.planets.push(planet);
      orbit *= 1.5 + rng.random() * 0.7;
    });

    return system;
  }

  /**
   * Register every patron system on a DataManager instance. Cheap: it builds
   * one system per named patron and touches nothing else, so the catalog can
   * list and target them without generating a whole galaxy first.
   */
  function ensureSystems(dataManager) {
    if (!dataManager || !dataManager.systems) return [];
    const out = [];
    for (const patron of PATRONS) {
      const name = systemNameFor(patron);
      let sys = dataManager.systems.get(name);
      if (!sys) {
        sys = buildPatronSystem(patron, dataManager);
        if (!sys) continue;
        dataManager.systems.set(name, sys);
      }
      out.push({ patron, system: sys });
    }
    return out;
  }

  /**
   * The star class, written out: the shared astronomy vocabulary in
   * js/i18n/<locale>/plugins/Astronomy.json, keyed on the slugged class name
   * the way Titlescreen's catalogues do it. A class with no entry reads as its
   * own id with the underscores taken out.
   */
  function starClassLabel(type) {
    const raw = String(type || "?");
    const key = "Astronomy.cls." + raw.toLowerCase().replace(/[^a-z0-9]+/g, "_");
    if (typeof T === "function" && T.has && T.has(key)) return T(key);
    return raw.replace(/_/g, " ");
  }

  /** Catalog rows for the star map's "Patrons" tab, by world name. */
  function catalogEntries(dataManager) {
    return ensureSystems(dataManager)
      .sort((a, b) => String(a.patron.planetName).localeCompare(String(b.patron.planetName)))
      .map(({ patron, system }) => {
        const world = (system.planets || []).find((p) => p.life === true) || system.planets[0];
        return {
          patron, system, planet: world,
          name: patron.planetName,
          // Their galaxy is everybody's galaxy now, so the row carries the
          // one thing that still tells these worlds apart at a glance: how far
          // out into the arm the patron's star sits.
          sub: patron.name + " · " + starClassLabel(system.type) + " · " +
            Math.round(starDistance(patron)) + " " + T('Astronomy.field.lightYears'),
        };
      });
  }

  // --- Hook: a patron system is a member of the home galaxy ------------------
  // getAllSystems is the one door every consumer goes through: the galaxy view
  // builds its star cloud from it, the catalog reads it, the refuel sweep
  // walks it. Registering the patron systems there makes them ordinary
  // inhabitants of the Milky Way with no other code aware of them. It is cheap
  // enough to run on every call: ensureSystems only builds a system the first
  // time it is asked for and does a map lookup after that.
  function hookSystemRegistry() {
    const DM = GS() && GS().DataManager;
    if (!DM || !DM.prototype || DM.prototype._patronSystemsHooked) return false;
    const _getAllSystems = DM.prototype.getAllSystems;
    DM.prototype.getAllSystems = function () {
      const list = _getAllSystems.call(this);
      if (!this._patronSystemsReady) {
        this._patronSystemsReady = true;
        // ensureSystems calls nothing that re-enters getAllSystems.
        const added = ensureSystems(this);
        if (added.length) return _getAllSystems.call(this);
      }
      return list;
    };
    DM.prototype._patronSystemsHooked = true;
    return true;
  }
  hookSystemRegistry();

  // ==========================================================================
  // Plugin command
  // ==========================================================================
  // Deliberately prints no coordinates: they are not in the database, and the
  // report is not the place to leak them. It reports the square the party is
  // standing on, and nothing about anybody else's.
  // i18n-ignore-start: developer console report, never shown to a player
  PluginManager.registerCommand(PLUGIN_NAME, "report", () => {
    for (const p of PATRONS) {
      log(`${p.name} (${p.id}) · ${p.biome || "?"} · vault ${VAULT_BIOME} · ` +
        `${p.planetName} in ${p.galaxy} (${systemNameFor(p)})`);
    }
    log(`${PATRONS.length} patrons, ${RESERVED} reserved slots waiting for a name`);
    const here = currentWorldCoords();
    const rec = here ? patronRecordAtWorld(here.x, here.y) : null;
    log(rec
      ? `this square belongs to ${rec.patron.name}: hatch at ${rec.mapCoordinates.join(",")}`
      : "this square belongs to no patron");
  });
  // i18n-ignore-end

  // The vault's floors are told to the house system at boot, not only when the
  // hatch is opened: a party standing on one of them without a session behind
  // it (a map opened from the editor, a debug teleport, an old save) still has
  // working stairs and a working elevator.
  const _PR_Scene_Boot_start = Scene_Boot.prototype.start;
  Scene_Boot.prototype.start = function () {
    _PR_Scene_Boot_start.call(this);
    const PHS = window.ProceduralHouseSystem;
    if (PHS && typeof PHS.registerFixedStack === "function") {
      PHS.registerFixedStack(VAULT_FLOORS, {
        key: "patronvault",  // i18n-ignore  stack id
        descending: true,
        // Climbing out of a vault nobody entered by the hatch: the way out is
        // a hatch all the same. It is THIS party's own hatch - the square the
        // vault origin proved, or the last patron square recognised - and only
        // a random known one where there is no own hatch to name, so a party
        // that knows two patron squares never surfaces on the wrong one.
        exitFallback: () => surfaceOnHatch(ownHatch()) || surfaceOnRandomHatch(),
      });
    }
  };

  // ==========================================================================
  // Public API
  // ==========================================================================
  window.PatreonRewards = {
    LOOT_RARITY_BONUS,
    // The public half only: the encrypted blob stays inside the plugin.
    patrons: () => PATRONS.map(({ secret, ...rest }) => rest),
    VAULT_BIOME,
    VAULT_FLOORS,
    VAULT_ENTRY,
    vaultHouseId,
    patronAtWorld,
    patronById,
    hatchTileAtWorld,
    hatchKeepOutRect,
    knownHatches,
    randomKnownHatch,
    surfaceOnRandomHatch,
    surfaceSealed,
    saySealed,
    ownHatch,
    surfaceOnHatch,
    goToOwnHatch,
    claimedSquare,
    claimSquare,
    grantVessel,
    VESSEL_ITEM_ID,
    applyMapFeatures,
    stampLiveMap,
    stampWindowCells,
    squareOfMapTile,
    openHatch,
    tryHatchUnderfoot,
    isPatronHatch: (tile) => !!patronOfHatchTile(tile),
    isInPatronVault,
    vaultPatron,
    vaultFloorPatron,
    populateVaultFloor,
    randomVaultFloor,
    lootRarityBonus,
    containerTierWeight,
    ensureSystems,
    catalogEntries,
    systemNameFor,
    starPosition,
    starDistance,
  };
})();
