/*:
 * @target MZ
 * @plugindesc World Atlas: the political map of the world, drawn as SVG from WorldGen/Countries.json
 * @author Omni-Lex
 *
 * @command openAtlas
 * @text Open World Atlas
 * @desc Opens the political atlas of the world.
 *
 * @help WorldAtlas.js
 *
 * The atlas every nation in js/db/WorldGen/Countries.json is painted on. It is
 * NOT the travel map (Map/WorldMap.js): nothing here teleports anybody, it is
 * the reference sheet that says who holds what and what the weather does there.
 *
 * === The world it draws ===
 * Geometry lives in js/db/WorldGen/Atlas.json, generated by tools/atlas/
 * gen_atlas.py from Natural Earth 50m (public domain). Two layers:
 *   - "land": every coast still standing, drawn as unclaimed ground.
 *   - "shapes": one entry per country, drawn over the land and coloured by
 *     whoever holds it.
 *
 * The Americas are gone. What stands in their place is Canadafrica: Canada
 * fused to a second Africa-shaped landmass that carries the old United States
 * (Cascadia Protectorate, Free States of Midwest, Eastern Seaboard) across its
 * northern belt and the whole of South America below it. Chile runs the entire
 * east coast of that continent as one long ribbon, which is why its hyperpower
 * is called Long Chile.
 *
 * === Controls ===
 * Mouse:    drag to pan, wheel to zoom, hover to read, click to select.
 * Arrows/WASD: pan.  PageUp/PageDown: step through the nations.
 * OK: centre on the selected nation.  Shift: cycle the shading.
 * Cancel/Esc: close.
 *
 * === Opening it ===
 * Pause menu -> World Map -> Atlas, the plugin command above, or
 * window.WorldAtlas.open() from a script call.
 */

(() => {
    "use strict";

    const PLUGIN = "WorldAtlas";

    // ── data ────────────────────────────────────────────────────────────────

    const atlasData = () => (window.WorldGen && window.WorldGen.Atlas) || null;
    const countryList = () => (window.WorldGen && window.WorldGen.Countries) || [];

    // Countries.json ids, never shown as they are written here.
    // i18n-ignore-start
    const NEUTRAL = "Neutral";
    const OMEGA_TOWER = "OmegaTower";
    const REGION_KEYS = {
        "Europe": "europe",
        "Asia": "asia",
        "Middle East": "middleEast",
        "North America": "northAmerica",
        "South America": "southAmerica",
        "Africa": "africa",
        "Oceania": "oceania",
    };
    const SEASONS = ["winter", "spring", "summer", "autumn"];
    // i18n-ignore-end

    // Map inks. Colours are not text: they stay here rather than in the i18n
    // files. One per hyperpower, so a holding reads the same on every screen.
    const POWER_INK = {
        "Neutral": "#b9ad91",
        "Holy Vatican Empire": "#c9a227",
        "Britannia": "#8c5a9e",
        "USSR": "#b23a3a",
        "Soviet Union": "#b23a3a",
        "Archive Foundation": "#5d7a8c",
        "Ottoman Empire": "#2f7d5f",
        "Goblin Horde": "#7a8c3a",
        "Mages Guild": "#4a6fb5",
        "The Gods": "#d1743c",
        "Hypercapitalist Collective": "#3f9e8a",
        "San Marino Republic": "#9e6b4a",
        "Continental Union": "#6f8fd1",
        "Kukulkan Ascendancy": "#a2543f",
        "Long Chile": "#8fbf5a",
        "Dharma Directorate": "#c98a3c",
        "Democratic People's Republic of Korea": "#96403f",
        "Illuminated Khanate": "#a58cc4",
        "Sanatana Rashtra": "#d09a4e",
        "Imperial State of Persia": "#4f8f9e",
        "Solomonic Republic": "#6fa04a",
        "Petro Kingdom of Arabia": "#3c6b4f",
        "Free States of Midwest": "#6f8fd1",
        "Cascadia Protectorate": "#9a7fb5",
        "Eastern Seaboard": "#a25f7a",
        "The Dargos": "#7a4a6b",
        "The Tourists": "#c46f8c",
    };

    const REGION_INK = {
        "Europe": "#c9a227",
        "Asia": "#3f9e8a",
        "Middle East": "#c98a3c",
        "North America": "#6f8fd1",
        "South America": "#8fbf5a",
        "Africa": "#a2543f",
        "Oceania": "#8c5a9e",
    };

    // An unlisted holder (a mod, a hyperpower added later) still needs an ink
    // of its own, and it must be the same ink every time the atlas opens.
    function hashedInk(name) {
        let h = 0;
        for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) | 0;
        const hue = Math.abs(h) % 360;
        return `hsl(${hue}, 34%, 52%)`;
    }

    function powerInk(name) {
        if (!name) return POWER_INK[NEUTRAL];
        return POWER_INK[name] || hashedInk(name);
    }

    // Who actually holds the ground: the controller when there is one, the
    // faction the nation belongs to otherwise.
    function holderOf(country) {
        const ctrl = country.controller;
        if (ctrl && ctrl !== NEUTRAL) return ctrl;
        const fac = country.faction;
        if (fac && fac !== NEUTRAL) return fac;
        return NEUTRAL;
    }

    // Temperature shading: cold blue to hot red along one ramp, shared by the
    // map and by the legend under it so the two cannot drift apart.
    function rampInk(t) {
        const k = Math.max(0, Math.min(1, t));
        return `hsl(${Math.round(220 - 220 * k)}, 55%, ${Math.round(62 - 28 * Math.abs(k - 0.5))}%)`;
    }

    // The current season's daytime high, over the range the country table
    // actually covers (-28 to 43).
    function climateInk(country, season) {
        const s = country.seasons && country.seasons[season];
        if (!s || typeof s.dayTemp !== "number") return POWER_INK[NEUTRAL];
        return rampInk((s.dayTemp + 28) / 71);
    }

    // ── names ───────────────────────────────────────────────────────────────

    const nationLabel = (id) => (window.WorldNames ? window.WorldNames.nation(id) : String(id || ""));
    const powerLabel = (id) => {
        if (!id) return "";
        return window.WorldNames ? window.WorldNames.power(id) : String(id);
    };
    const regionLabel = (region) => {
        const key = REGION_KEYS[region];
        return key ? T("Atlas.region." + key) : String(region || "");
    };
    const seasonLabel = (season) => T("Atlas.season." + season);

    function escHtml(str) {
        return String(str === undefined || str === null ? "" : str)
            .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;");
    }

    // ── world state ─────────────────────────────────────────────────────────

    function activeSeason() {
        try {
            if (typeof $gameWeather !== "undefined" && $gameWeather &&
                typeof $gameWeather.getSeason === "function") {
                const s = String($gameWeather.getSeason()).toLowerCase();
                if (SEASONS.indexOf(s) >= 0) return s;
            }
        } catch (e) { /* no weather yet: fall through */ }
        return SEASONS[0];
    }

    // The nation the party is standing in, as WeatherSystem worked it out.
    function partyCountryName() {
        try {
            if (typeof $gameWeather !== "undefined" && $gameWeather && $gameWeather.currentCountry) {
                return $gameWeather.currentCountry.country || null;
            }
            const id = (typeof $gameVariables !== "undefined" && $gameVariables)
                ? $gameVariables.value(86) : 0;
            const hit = countryList().find((c) => c.id === id);
            return hit ? hit.country : null;
        } catch (e) {
            return null;
        }
    }

    // Where the party stands, in atlas degrees, when that can be answered
    // exactly: the world map's own squares run through the affine fit baked
    // into Atlas.json. Anywhere else the party is placed by their country.
    function partyPoint() {
        const data = atlasData();
        const wm = window.WorldMapTransfer;
        if (!data || !data.worldTile || !wm) return null;
        try {
            if (!$gameMap || $gameMap.mapId() !== wm.worldMapId) {
                const pos = wm.currentWorldCoords && wm.currentWorldCoords();
                if (!pos) return null;
                return applyWorldTile(data.worldTile.matrix, pos.x, pos.y);
            }
            return applyWorldTile(data.worldTile.matrix, $gamePlayer.x, $gamePlayer.y);
        } catch (e) {
            return null;
        }
    }

    function applyWorldTile(m, x, y) {
        if (!Array.isArray(m) || m.length < 6) return null;
        return [m[0] * x + m[1] * y + m[2], m[3] * x + m[4] * y + m[5]];
    }

    // ── geometry, built once per session ────────────────────────────────────

    let _built = null;

    function buildGeometry() {
        if (_built) return _built;
        const data = atlasData();
        if (!data || !data.shapes) return null;

        const path = (rings) => {
            let d = "";
            for (let r = 0; r < rings.length; r++) {
                const ring = rings[r];
                for (let i = 0; i < ring.length; i++) {
                    d += (i ? "L" : "M") + ring[i][0] + " " + (-ring[i][1]);
                }
                d += "Z";
            }
            return d;
        };

        const bounds = (rings) => {
            let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
            rings.forEach((ring) => ring.forEach((p) => {
                if (p[0] < x0) x0 = p[0];
                if (p[0] > x1) x1 = p[0];
                if (p[1] < y0) y0 = p[1];
                if (p[1] > y1) y1 = p[1];
            }));
            return { w: x1 - x0, h: y1 - y0 };
        };

        const shapes = {};
        Object.keys(data.shapes).forEach((name) => {
            const rings = data.shapes[name];
            const b = bounds(rings);
            shapes[name] = { d: path(rings), size: Math.max(b.w, b.h) };
        });

        // The world before the Squishing, for everything that moved.
        const legacy = {};
        Object.keys(data.legacy || {}).forEach((name) => {
            const rings = data.legacy[name];
            const b = bounds(rings);
            legacy[name] = { d: path(rings), size: Math.max(b.w, b.h) };
        });

        _built = {
            land: Array.isArray(data.land) ? path(data.land) : "",
            americas: Array.isArray(data.americas) ? path(data.americas) : "",
            canadafrica: Array.isArray(data.canadafrica) ? path(data.canadafrica) : "",
            landMorph: data.landMorph || null,
            shapes,
            legacy,
            morph: data.morph || {},
            anchors: data.anchors || {},
            legacyAnchors: data.legacyAnchors || {},
            notes: data.notes || {},
            markers: data.markers || {},
            era: (data.meta && data.meta.era) || { legacyUntil: 1992, settledFrom: 1994 },
        };
        return _built;
    }

    // A shape halfway between the two worlds. Both sides are written as the
    // same run of points (tools/atlas/gen_atlas.py resamples them), so the
    // change is one lerp per point.
    function morphPath(pair, t) {
        let d = "";
        for (let r = 0; r < pair.from.length; r++) {
            const a = pair.from[r], b = pair.to[r];
            const n = Math.min(a.length, b.length);
            for (let i = 0; i < n; i++) {
                const x = a[i][0] + (b[i][0] - a[i][0]) * t;
                const y = a[i][1] + (b[i][1] - a[i][1]) * t;
                d += (i ? "L" : "M") + x.toFixed(2) + " " + (-y).toFixed(2);
            }
            d += "Z";
        }
        return d;
    }

    // ── the century ─────────────────────────────────────────────────────────

    const FIRST_YEAR = 1900;

    // The year the party is living in. The atlas never reads past it: the map
    // is a record of what happened, not a forecast.
    function currentGameYear() {
        try {
            const TD = window.TimeDateSystem;
            if (TD && typeof TD.getCurrentDateObj === "function") {
                const y = TD.getCurrentDateObj().getFullYear();
                if (Number.isFinite(y)) return Math.max(FIRST_YEAR, y);
            }
        } catch (e) { /* the clock is not up yet */ }
        return 2001;
    }

    // How far through the change a year stands: 0 the world before, 1 the world
    // after, in between while the western hemisphere is being replaced.
    function eraProgress(year, era) {
        const from = era.legacyUntil, to = era.settledFrom;
        if (year <= from) return 0;
        if (year >= to) return 1;
        return (year - from) / (to - from);
    }

    // Who held a nation in a given year, read off the century the
    // HistorySimulator ran. A world that has never been simulated answers with
    // the country table, which is where it started.
    function controllerAt(country, year, cache) {
        const line = nationTimeline(country, cache);
        let held = null;
        for (let i = 0; i < line.length; i++) {
            if (line[i].year > year) break;
            held = line[i].controller;
        }
        if (held) return held;
        const entry = countryList().find((c) => c.country === country);
        return entry ? holderOf(entry) : NEUTRAL;
    }

    // Every time a nation changed hands, as [{year, controller}]. Read once per
    // nation per visit: the slider asks for this on every step.
    function nationTimeline(country, cache) {
        if (cache && cache[country]) return cache[country];
        let line = [];
        try {
            const HM = window.HistoryManager;
            const recs = (HM && HM.getNationHistory) ? HM.getNationHistory(country) : [];
            line = (recs || []).map((r) => ({
                year: parseInt(String(r.date).slice(0, 4), 10) || FIRST_YEAR,
                controller: r.controller || NEUTRAL,
                reason: r.reason || "",
            })).sort((a, b) => a.year - b.year);
        } catch (e) {
            line = [];
        }
        if (cache) cache[country] = line;
        return line;
    }

    // ── the scene ───────────────────────────────────────────────────────────

    const CONTAINER_ID = "world-atlas-container";
    const MODES = ["power", "region", "climate"];
    const WORLD = { minLon: -172, maxLon: 180, minLat: -58, maxLat: 84 };
    const MIN_SPAN = 6;
    const LABEL_PX = 46;      // a nation is named once it is this wide on screen
    class Scene_WorldAtlas extends Scene_MenuBase {
        create() {
            super.create();
            this._geo = buildGeometry();
            this._mode = MODES[0];
            this._season = activeSeason();
            this._entries = countryList()
                .filter((c) => c && c.country && this._geo && this._geo.shapes[c.country])
                .sort((a, b) => nationLabel(a.country).localeCompare(nationLabel(b.country)));
            this._byName = {};
            this._entries.forEach((c) => { this._byName[c.country] = c; });
            this._selected = partyCountryName();
            if (!this._byName[this._selected]) this._selected = null;
            this._hovered = null;
            this._focusHolder = null;
            this._view = null;
            this._el = null;
            // The atlas opens on the day the party is living, and reads back
            // from there. Nothing past today is ever drawn.
            this._today = currentGameYear();
            this._year = this._today;
            this._histCache = {};
            this._era = this._geo ? this._geo.era : { legacyUntil: 1992, settledFrom: 1994 };
            this._buildDOM();
        }

        // ── DOM ─────────────────────────────────────────────────────────────

        _buildDOM() {
            const el = document.createElement("div");
            el.id = CONTAINER_ID;
            el.innerHTML = `
                <div class="book-spread">
                    <div class="left-page wa-map-page">
                        <div class="page-header-bar">
                            <div class="back-button focusable" id="wa-back" tabindex="0">${escHtml(T("Atlas.back"))}</div>
                            <h2 class="title">${escHtml(T("Atlas.title"))}</h2>
                        </div>
                        <div class="backpack-tabs wa-modes">${this._modeButtons()}</div>
                        <div class="wa-frame" id="wa-frame">${this._svg()}</div>
                        <div class="wa-years">
                            <span class="inspect-btn wa-step focusable" id="wa-year-back" tabindex="0">&#9664;</span>
                            <input class="wa-slider" id="wa-year-slider" type="range"
                                   min="${FIRST_YEAR}" max="${this._today}" step="1" value="${this._year}">
                            <span class="inspect-btn wa-step focusable" id="wa-year-fwd" tabindex="0">&#9654;</span>
                            <span class="wa-year-readout" id="wa-year-readout">${this._year}</span>
                            <span class="wa-year-era" id="wa-year-era">${escHtml(this._eraLabel())}</span>
                            <span class="inspect-btn focusable" id="wa-year-now" tabindex="0">${escHtml(T("Atlas.today"))}</span>
                        </div>
                        <div class="wa-legend ui-scroll" id="wa-legend">${this._legend()}</div>
                    </div>
                    <div class="right-page">
                        <div class="ui-detail" id="wa-dossier">${this._dossier()}</div>
                        <div class="ui-footer">${escHtml(T("Atlas.countLabel", { n: this._entries.length }))}</div>
                    </div>
                </div>`;
            document.body.appendChild(el);
            this._el = el;
            // Panning moves the viewBox every frame, so nothing on that path is
            // allowed to search the document: every node it touches is looked
            // up once, here.
            this._dom = {
                frame: el.querySelector("#wa-frame"),
                svg: el.querySelector("#wa-svg"),
                labels: el.querySelector("#wa-labels"),
                tower: el.querySelector("#wa-tower-mark"),
                pin: el.querySelector("#wa-party-mark"),
                dossier: el.querySelector("#wa-dossier"),
                legend: el.querySelector("#wa-legend"),
                slider: el.querySelector("#wa-year-slider"),
                readout: el.querySelector("#wa-year-readout"),
                eraLabel: el.querySelector("#wa-year-era"),
                landStatic: el.querySelector("#wa-land"),
                americas: el.querySelector("#wa-americas"),
                canadafrica: el.querySelector("#wa-canadafrica"),
                landMorph: el.querySelector("#wa-land-morph"),
            };
            this._countryNodes = {};
            el.querySelectorAll(".wa-country").forEach((node) => {
                this._countryNodes[node.dataset.c] = node;
            });
            this._labelNodes = Array.from(el.querySelectorAll(".wa-label"));
            this._size = null;
            this._onResize = () => { this._size = null; this._applyView(); };
            window.addEventListener("resize", this._onResize);
            this._attachEvents();
            this._resetView();
            setTimeout(() => { if (this._el) this._el.classList.add("wa-open"); }, 16);
        }

        _modeButtons() {
            return MODES.map((m) =>
                `<div class="backpack-tab wa-mode focusable${m === this._mode ? " active" : ""}" data-mode="${m}" tabindex="0">` +
                `${escHtml(T("Atlas.mode." + m))}</div>`).join("");
        }

        _svg() {
            if (!this._geo) return `<p class="ui-empty-text">${escHtml(T("Atlas.noData"))}</p>`;
            const grid = [];
            for (let lon = -180; lon <= 180; lon += 20) {
                grid.push(`<path class="wa-grid" d="M${lon} -90L${lon} 90"/>`);
            }
            for (let lat = -80; lat <= 80; lat += 20) {
                grid.push(`<path class="wa-grid" d="M-180 ${-lat}L180 ${-lat}"/>`);
            }
            const shapes = this._entries.map((c) => {
                const frag = this._geo.notes[c.country] === "fragment" ? " wa-fragment" : "";
                // Every outline is written by _applyEra: which of the two worlds
                // a nation is drawn in depends on the year the slider is on.
                return `<path class="wa-country${frag}" data-c="${escHtml(c.country)}" d=""/>`;
            }).join("");
            const labels = this._entries.map((c) => {
                const a = this._geo.anchors[c.country];
                if (!a) return "";
                return `<text class="wa-label" data-c="${escHtml(c.country)}" x="${a[0]}" y="${-a[1]}"` +
                    ` display="none">${escHtml(nationLabel(c.country))}</text>`;
            }).join("");
            const tower = this._geo.markers[OMEGA_TOWER];
            const towerMark = tower
                ? `<path class="wa-tower" id="wa-tower-mark" d="${this._diamond(tower[0], -tower[1], 1.6)}"/>` : "";
            return `<svg id="wa-svg" preserveAspectRatio="xMidYMid meet">
                <rect class="wa-ocean" x="-200" y="-100" width="400" height="200"/>
                <g>${grid.join("")}</g>
                <path class="wa-land" id="wa-land" d="${this._geo.land}"/>
                <path class="wa-land" id="wa-americas" d="${this._geo.americas}" display="none"/>
                <path class="wa-land" id="wa-canadafrica" d="${this._geo.canadafrica}" display="none"/>
                <path class="wa-land" id="wa-land-morph" d="" display="none"/>
                <g id="wa-countries">${shapes}</g>
                <g id="wa-marks">${towerMark}<path class="wa-pin" id="wa-party-mark" d="" display="none"/></g>
                <g id="wa-labels" font-size="3">${labels}</g>
            </svg>`;
        }

        _diamond(x, y, r) {
            return `M${x} ${y - r}L${x + r} ${y}L${x} ${y + r}L${x - r} ${y}Z`;
        }

        _legend() {
            const seen = [];
            const push = (key, ink) => {
                if (!seen.some((s) => s.key === key)) seen.push({ key, ink });
            };
            if (this._mode === "power") {
                this._entries.forEach((c) => {
                    const held = this._holderOf(c);
                    push(held, powerInk(held));
                });
                // Held ground first, in the player's alphabet; the unaligned
                // rest is one entry at the end.
                seen.sort((a, b) => {
                    if (a.key === NEUTRAL) return 1;
                    if (b.key === NEUTRAL) return -1;
                    return powerLabel(a.key).localeCompare(powerLabel(b.key));
                });
            } else if (this._mode === "region") {
                this._entries.forEach((c) => push(c.region, REGION_INK[c.region] || hashedInk(c.region)));
            } else {
                const steps = T.list("Atlas.climateScale");
                return steps.map((label, i) =>
                    `<div class="wa-legend-item ui-chip" style="--wa-ink:${rampInk(i / Math.max(1, steps.length - 1))}">` +
                    `<span class="wa-swatch"></span>${escHtml(label)}</div>`).join("");
            }
            return seen.map((s) => {
                const label = this._mode === "power"
                    ? (s.key === NEUTRAL ? T("Atlas.unaligned") : powerLabel(s.key))
                    : regionLabel(s.key);
                const muted = this._focusHolder && this._focusHolder !== s.key ? " muted" : "";
                return `<div class="wa-legend-item ui-chip focusable${muted}" data-key="${escHtml(s.key)}"` +
                    ` tabindex="0" style="--wa-ink:${s.ink}">` +
                    `<span class="wa-swatch"></span>${escHtml(label)}</div>`;
            }).join("");
        }

        // ── right page ──────────────────────────────────────────────────────

        _dossier() {
            const name = this._selected;
            const c = name ? this._byName[name] : null;
            if (!c) {
                return `<div class="ui-empty"><p class="ui-empty-text">` +
                    `${escHtml(T("Atlas.selectPrompt"))}</p></div>`;
            }

            const holder = this._holderOf(c);
            const holderName = holder === NEUTRAL ? T("Atlas.unaligned") : powerLabel(holder);
            const here = partyCountryName() === name && this._year === this._today
                ? `<span class="ui-chip">${escHtml(T("Atlas.here"))}</span>` : "";
            const fragment = this._geo && this._geo.notes[name] === "fragment"
                ? `<p class="ui-prose">${escHtml(T("Atlas.fragment"))}</p>` : "";
            const rows = [
                [T("Atlas.field.region"), regionLabel(c.region)],
                [T("Atlas.field.heldIn", { year: this._year }), holderName],
                [T("Atlas.field.faction"), c.faction === NEUTRAL ? T("Atlas.unaligned") : powerLabel(c.faction)],
            ].map(([k, v]) =>
                `<div class="inspect-spec-row"><span class="inspect-spec-label">${escHtml(k)}</span>` +
                `<span class="inspect-spec-value">${escHtml(v)}</span></div>`).join("");

            const wiki = window.NPCEmpathize && typeof window.NPCEmpathize.openEntity === "function"
                ? `<div class="inspect-actions"><div class="inspect-btn focusable" id="wa-wiki" tabindex="0">` +
                  `${escHtml(T("Atlas.openArticle"))}</div></div>`
                : "";

            return `
                <div class="ui-detail-head">
                    <span class="wa-swatch wa-swatch--large" style="--wa-ink:${powerInk(holder)}"></span>
                    <div class="ui-detail-titles">
                        <h3>${escHtml(nationLabel(name))}</h3>
                        <div class="ui-detail-sub">${escHtml(holderName)}</div>
                    </div>
                    ${here}
                </div>
                <div class="ui-detail-scroll">
                    <div class="inspect-spec-grid">${rows}</div>
                    ${fragment}
                    ${this._handsHTML(name)}
                    <div class="inspect-section-title">${escHtml(T("Atlas.field.climate"))}</div>
                    ${this._climateTable(c)}
                </div>
                ${wiki}`;
        }

        // Every time this nation changed hands, up to the year on the slider.
        // A world that has never run its century has nothing to say here.
        _handsHTML(name) {
            const line = nationTimeline(name, this._histCache).filter((r) => r.year <= this._year);
            if (line.length < 2) return "";
            const rows = line.slice(-8).reverse().map((r) =>
                `<div class="inspect-spec-row"><span class="inspect-spec-label">${r.year}</span>` +
                `<span class="inspect-spec-value">` +
                `${escHtml(r.controller === NEUTRAL ? T("Atlas.unaligned") : powerLabel(r.controller))}</span></div>`
            ).join("");
            return `<div class="inspect-section-title">${escHtml(T("Atlas.field.changedHands"))}</div>` +
                `<div class="inspect-spec-grid">${rows}</div>`;
        }

        _climateTable(c) {
            if (!c.seasons) return `<p class="ui-empty-note">${escHtml(T("Atlas.noClimate"))}</p>`;
            const num = (v, digits) => (typeof v === "number" ? v.toFixed(digits === undefined ? 1 : digits) : "-");
            const rows = [
                [T("Atlas.climate.dayTemp"), (s) => T("Atlas.units.temp", { value: num(s.dayTemp) })],
                [T("Atlas.climate.nightTemp"), (s) => T("Atlas.units.temp", { value: num(s.nightTemp) })],
                [T("Atlas.climate.precipitation"), (s) => T("Atlas.units.mm", { value: num(s.precipitation) })],
                [T("Atlas.climate.wind"), (s) => T("Atlas.units.speed", { value: num(s.windSpeed) })],
                [T("Atlas.climate.cloud"), (s) => T("Atlas.units.percent", { value: num(s.cloudCover, 0) })],
                [T("Atlas.climate.humidity"), (s) => T("Atlas.units.percent", { value: num(s.dayHumidity, 0) })],
                [T("Atlas.climate.daylight"), (s) => `${s.sunrise || "-"} - ${s.sunset || "-"}`],
            ];
            const cols = SEASONS.map((s) =>
                `<col class="${s === this._season ? "wa-now" : ""}"/>`).join("");
            const head = SEASONS.map((s) => `<th>${escHtml(seasonLabel(s))}</th>`).join("");
            const body = rows.map(([label, cell]) =>
                `<tr><td>${escHtml(label)}</td>` + SEASONS.map((s) => {
                    const data = c.seasons[s];
                    return `<td>${escHtml(data ? cell(data) : "-")}</td>`;
                }).join("") + `</tr>`).join("");
            return `<table class="wa-climate"><colgroup><col/>${cols}</colgroup>` +
                `<thead><tr><th></th>${head}</tr></thead><tbody>${body}</tbody></table>`;
        }

        // ── the view box ────────────────────────────────────────────────────

        // Measured once and kept: reading it back every frame of a drag would
        // force a layout pass per pointer move. The resize listener clears it.
        _frameSize() {
            if (this._size) return this._size;
            const frame = this._dom && this._dom.frame;
            if (!frame) return { w: 1, h: 1 };
            const r = frame.getBoundingClientRect();
            this._size = { w: Math.max(1, r.width), h: Math.max(1, r.height) };
            return this._size;
        }

        _resetView() {
            const size = this._frameSize();
            const worldW = WORLD.maxLon - WORLD.minLon;
            const worldH = WORLD.maxLat - WORLD.minLat;
            // Fit whichever axis is tighter, so the whole world is on the page.
            const w = Math.max(worldW, worldH * (size.w / size.h));
            this._view = {
                cx: (WORLD.minLon + WORLD.maxLon) / 2,
                cy: -(WORLD.minLat + WORLD.maxLat) / 2,
                w,
            };
            this._applyView();
        }

        _applyView() {
            const svg = this._dom && this._dom.svg;
            if (!svg || !this._view) return;
            const size = this._frameSize();
            const v = this._view;
            const maxW = (WORLD.maxLon - WORLD.minLon) * 1.2;
            v.w = Math.max(MIN_SPAN, Math.min(maxW, v.w));
            const h = v.w * (size.h / size.w);
            v.cx = Math.max(WORLD.minLon - 20, Math.min(WORLD.maxLon + 20, v.cx));
            v.cy = Math.max(-WORLD.maxLat - 20, Math.min(-WORLD.minLat + 20, v.cy));
            svg.setAttribute("viewBox", `${v.cx - v.w / 2} ${v.cy - h / 2} ${v.w} ${h}`);

            // Everything drawn at a constant on-screen size is re-scaled here:
            // the viewBox is in degrees, so one screen pixel is worth fewer
            // degrees the further the atlas is zoomed in.
            const perPx = v.w / size.w;
            if (this._dom.labels) this._dom.labels.setAttribute("font-size", (11 * perPx).toFixed(3));
            this._updateLabels(perPx);
            this._updateMarks(perPx);
        }

        // A nation is named only when there is room to read it, and only while
        // it is on the page.
        _updateLabels(perPx) {
            if (!this._geo) return;
            const v = this._view;
            const size = this._frameSize();
            const h = v.w * (size.h / size.w);
            const x0 = v.cx - v.w / 2, x1 = v.cx + v.w / 2;
            const y0 = v.cy - h / 2, y1 = v.cy + h / 2;
            (this._labelNodes || []).forEach((node) => {
                const name = node.dataset.c;
                const shape = this._geo.shapes[name];
                const a = this._geo.anchors[name];
                if (!shape || !a) return;
                const visible = shape.size / perPx >= LABEL_PX &&
                    a[0] >= x0 && a[0] <= x1 && -a[1] >= y0 && -a[1] <= y1;
                node.setAttribute("display", visible ? "inline" : "none");
            });
        }

        _updateMarks(perPx) {
            const tower = this._dom.tower;
            const data = this._geo && this._geo.markers[OMEGA_TOWER];
            const r = Math.max(0.35, 7 * perPx);
            if (tower && data) tower.setAttribute("d", this._diamond(data[0], -data[1], r));
            const pin = this._dom.pin;
            if (!pin) return;
            const point = partyPoint();
            if (!point) { pin.setAttribute("display", "none"); return; }
            pin.setAttribute("display", "inline");
            const x = point[0], y = -point[1];
            pin.setAttribute("d", `M${x} ${y}L${x - r} ${y - r * 2.2}L${x + r} ${y - r * 2.2}Z`);
        }

        _zoomAt(factor, clientX, clientY) {
            const frame = this._dom && this._dom.frame;
            if (!frame || !this._view) return;
            const rect = frame.getBoundingClientRect();
            const before = this._toUser(clientX, clientY, rect);
            this._view.w *= factor;
            this._applyView();
            const after = this._toUser(clientX, clientY, rect);
            if (before && after) {
                this._view.cx += before.x - after.x;
                this._view.cy += before.y - after.y;
                this._applyView();
            }
        }

        _toUser(clientX, clientY, rect) {
            const v = this._view;
            if (!v) return null;
            const h = v.w * (rect.height / rect.width);
            return {
                x: v.cx - v.w / 2 + ((clientX - rect.left) / rect.width) * v.w,
                y: v.cy - h / 2 + ((clientY - rect.top) / rect.height) * h,
            };
        }

        _centreOn(name) {
            const a = this._geo && this._geo.anchors[name];
            if (!a || !this._view) return;
            const shape = this._geo.shapes[name];
            this._view.cx = a[0];
            this._view.cy = -a[1];
            if (shape) this._view.w = Math.max(MIN_SPAN, shape.size * 3.2);
            this._applyView();
        }

        // Pan just enough to bring a nation onto the page, leaving the zoom be.
        _revealSelected() {
            const a = this._geo && this._geo.anchors[this._selected];
            if (!a || !this._view) return;
            const size = this._frameSize();
            const v = this._view;
            const h = v.w * (size.h / size.w);
            const x = a[0], y = -a[1];
            const padX = v.w * 0.12, padY = h * 0.12;
            let moved = false;
            if (x < v.cx - v.w / 2 + padX) { v.cx = x + v.w / 2 - padX; moved = true; }
            if (x > v.cx + v.w / 2 - padX) { v.cx = x - v.w / 2 + padX; moved = true; }
            if (y < v.cy - h / 2 + padY) { v.cy = y + h / 2 - padY; moved = true; }
            if (y > v.cy + h / 2 - padY) { v.cy = y - h / 2 + padY; moved = true; }
            if (moved) this._applyView();
        }

        // ── painting ────────────────────────────────────────────────────────

        // ── the year ────────────────────────────────────────────────────────

        _eraLabel() {
            const t = eraProgress(this._year, this._era);
            if (t <= 0) return T("Atlas.era.before");
            if (t >= 1) return T("Atlas.era.after");
            return T("Atlas.era.during", { pct: Math.round(t * 100) });
        }

        // Where a nation is drawn this year, and where its name is written.
        _outlineOf(name) {
            const t = eraProgress(this._year, this._era);
            const pair = this._geo.morph[name];
            if (pair && t > 0 && t < 1) return morphPath(pair, t);
            if (t < 1 && this._geo.legacy[name]) return this._geo.legacy[name].d;
            const modern = this._geo.shapes[name];
            return modern ? modern.d : "";
        }

        _anchorOf(name) {
            const t = eraProgress(this._year, this._era);
            const now = this._geo.anchors[name];
            const was = this._geo.legacyAnchors[name] || now;
            if (!now) return was;
            if (t <= 0) return was;
            if (t >= 1) return now;
            return [was[0] + (now[0] - was[0]) * t, was[1] + (now[1] - was[1]) * t];
        }

        // Redraw the world for the year the slider stands on: the land that
        // moved, the nations that moved with it, and the labels that follow.
        _applyEra() {
            if (!this._geo || !this._dom) return;
            const t = eraProgress(this._year, this._era);
            const d = this._dom;
            const show = (node, on) => { if (node) node.setAttribute("display", on ? "inline" : "none"); };
            show(d.americas, t <= 0);
            show(d.canadafrica, t >= 1);
            show(d.landMorph, t > 0 && t < 1);
            if (d.landMorph && t > 0 && t < 1 && this._geo.landMorph) {
                d.landMorph.setAttribute("d", morphPath(this._geo.landMorph, t));
            }
            const nodes = this._countryNodes || {};
            Object.keys(nodes).forEach((name) => {
                nodes[name].setAttribute("d", this._outlineOf(name));
            });
            (this._labelNodes || []).forEach((node) => {
                const a = this._anchorOf(node.dataset.c);
                if (!a) return;
                node.setAttribute("x", a[0].toFixed(2));
                node.setAttribute("y", (-a[1]).toFixed(2));
            });
            if (d.readout) d.readout.textContent = String(this._year);
            if (d.eraLabel) d.eraLabel.textContent = this._eraLabel();
            if (d.slider && Number(d.slider.value) !== this._year) d.slider.value = String(this._year);
        }

        _setYear(year, playSound) {
            const next = Math.max(FIRST_YEAR, Math.min(this._today, Math.round(year)));
            if (next === this._year) return;
            this._year = next;
            if (playSound) SoundManager.playCursor();
            this._applyEra();
            this._paint();
            this._refreshLegend();
            this._refreshDossier();
            this._applyView();
        }

        // Who holds a nation in the year on the slider.
        _holderOf(country) {
            const held = controllerAt(country.country, this._year, this._histCache);
            return held || NEUTRAL;
        }

        // What a nation is shaded by, in the mode showing: the ink itself, and
        // the key the legend filters on.
        _inkOf(c) {
            if (this._mode === "region") {
                return { key: c.region, ink: REGION_INK[c.region] || hashedInk(c.region) };
            }
            if (this._mode === "climate") {
                return { key: null, ink: climateInk(c, this._season) };
            }
            const key = this._holderOf(c);
            return { key, ink: powerInk(key) };
        }

        // The whole map: only the shading mode and the legend filter change it.
        _paint() {
            const nodes = this._countryNodes || {};
            Object.keys(nodes).forEach((name) => {
                const c = this._byName[name];
                if (!c) return;
                const { key, ink } = this._inkOf(c);
                nodes[name].setAttribute("fill", ink);
                nodes[name].classList.toggle("dim", !!this._focusHolder && key !== this._focusHolder);
                nodes[name].classList.toggle("selected", name === this._selected);
                nodes[name].classList.toggle("hovered", name === this._hovered);
            });
        }

        // Hover and selection move between two nations, so they repaint two
        // nations: the mouse crosses dozens of borders a second.
        _mark(name, cls, on) {
            const node = name && this._countryNodes ? this._countryNodes[name] : null;
            if (node) node.classList.toggle(cls, on);
        }

        _refreshDossier() {
            if (this._dom && this._dom.dossier) this._dom.dossier.innerHTML = this._dossier();
        }

        _refreshLegend() {
            if (this._dom && this._dom.legend) this._dom.legend.innerHTML = this._legend();
        }

        _hover(name) {
            if (name === this._hovered) return;
            this._mark(this._hovered, "hovered", false);
            this._hovered = name;
            this._mark(name, "hovered", true);
        }

        _select(name, playSound) {
            if (!name || !this._byName[name] || name === this._selected) return;
            this._mark(this._selected, "selected", false);
            this._selected = name;
            this._mark(name, "selected", true);
            if (playSound) SoundManager.playCursor();
            this._refreshDossier();
        }

        _stepSelection(delta) {
            if (!this._entries.length) return;
            let idx = this._entries.findIndex((c) => c.country === this._selected);
            idx = (idx < 0 ? 0 : idx + delta + this._entries.length) % this._entries.length;
            this._select(this._entries[idx].country, true);
            this._revealSelected();
        }

        _setMode(mode) {
            if (MODES.indexOf(mode) < 0 || mode === this._mode) return;
            this._mode = mode;
            this._focusHolder = null;
            SoundManager.playCursor();
            this._el.querySelectorAll(".wa-mode").forEach((node) => {
                node.classList.toggle("active", node.dataset.mode === mode);
            });
            this._paint();
            this._refreshLegend();
        }

        // ── events ──────────────────────────────────────────────────────────

        _attachEvents() {
            const el = this._el;
            const frame = this._dom.frame;

            el.addEventListener("click", (ev) => {
                if (ev.target.closest("#wa-back")) { SoundManager.playCancel(); this.popScene(); return; }
                if (ev.target.closest("#wa-year-back")) { this._setYear(this._year - 1, true); return; }
                if (ev.target.closest("#wa-year-fwd")) { this._setYear(this._year + 1, true); return; }
                if (ev.target.closest("#wa-year-now")) { this._setYear(this._today, true); return; }
                // The nation's own article, in the same encyclopedia every other
                // wiki link in the game opens (NPCEmpathize).
                if (ev.target.closest("#wa-wiki")) {
                    if (this._selected && window.NPCEmpathize?.openEntity) {
                        SoundManager.playOk();
                        window.NPCEmpathize.openEntity("nation", encodeURIComponent(this._selected));
                    }
                    return;
                }
                const mode = ev.target.closest(".wa-mode");
                if (mode) { this._setMode(mode.dataset.mode); return; }
                const legend = ev.target.closest(".wa-legend-item");
                if (legend && legend.dataset.key !== undefined) {
                    this._focusHolder = this._focusHolder === legend.dataset.key ? null : legend.dataset.key;
                    SoundManager.playCursor();
                    this._paint();
                    this._refreshLegend();
                    return;
                }
                const country = ev.target.closest(".wa-country");
                if (country && !this._dragged) {
                    SoundManager.playOk();
                    this._select(country.dataset.c, false);
                }
            });

            // The engine swallows document wheel events, so the dossier and the
            // legend scroll by hand. Over the map the wheel zooms instead, and
            // that is handled on the frame itself.
            el.addEventListener("wheel", (ev) => {
                if (ev.target.closest("#wa-frame")) return;
                const box = ev.target.closest("#wa-dossier, #wa-legend");
                if (!box) return;
                ev.preventDefault();
                box.scrollTop += ev.deltaY;
            }, { passive: false });

            el.addEventListener("mouseover", (ev) => {
                const country = ev.target.closest(".wa-country");
                this._hover(country ? country.dataset.c : null);
            });

            const slider = this._dom.slider;
            if (slider) {
                slider.addEventListener("input", () => this._setYear(Number(slider.value), false));
                slider.addEventListener("change", () => this._setYear(Number(slider.value), true));
                // The slider is a real focusable control: let it keep the arrow
                // keys it needs instead of panning the map behind it.
                slider.addEventListener("mousedown", (ev) => ev.stopPropagation());
            }

            if (!frame) return;

            frame.addEventListener("wheel", (ev) => {
                ev.preventDefault();
                this._zoomAt(ev.deltaY > 0 ? 1.18 : 1 / 1.18, ev.clientX, ev.clientY);
            }, { passive: false });

            frame.addEventListener("pointerdown", (ev) => {
                this._drag = { x: ev.clientX, y: ev.clientY };
                this._dragged = false;
                frame.classList.add("dragging");
                frame.setPointerCapture(ev.pointerId);
            });

            frame.addEventListener("pointermove", (ev) => {
                if (!this._drag || !this._view) return;
                const rect = frame.getBoundingClientRect();
                const perPx = this._view.w / rect.width;
                const dx = ev.clientX - this._drag.x;
                const dy = ev.clientY - this._drag.y;
                if (Math.abs(dx) + Math.abs(dy) > 3) this._dragged = true;
                this._view.cx -= dx * perPx;
                this._view.cy -= dy * perPx;
                this._drag = { x: ev.clientX, y: ev.clientY };
                this._applyView();
            });

            const endDrag = (ev) => {
                if (!this._drag) return;
                this._drag = null;
                frame.classList.remove("dragging");
                if (ev && ev.pointerId !== undefined && frame.hasPointerCapture(ev.pointerId)) {
                    frame.releasePointerCapture(ev.pointerId);
                }
                // The click that ends a drag must not also select a country.
                setTimeout(() => { this._dragged = false; }, 0);
            };
            frame.addEventListener("pointerup", endDrag);
            frame.addEventListener("pointercancel", endDrag);
        }

        // ── input loop ──────────────────────────────────────────────────────

        update() {
            super.update();
            if (!this._view) return;
            // WASD arrives here as the direction symbols: the keyMapper maps
            // them globally, so there is nothing else to listen for.
            const step = this._view.w * 0.02;
            let moved = false;
            if (Input.isPressed("right")) { this._view.cx += step; moved = true; }
            if (Input.isPressed("left")) { this._view.cx -= step; moved = true; }
            if (Input.isPressed("down")) { this._view.cy += step; moved = true; }
            if (Input.isPressed("up")) { this._view.cy -= step; moved = true; }
            if (moved) this._applyView();

            // The century is stepped with PageUp/PageDown, ten years at a time
            // while a direction is held; Tab walks the nations instead.
            const leap = Input.isPressed("control") ? 10 : 1;
            if (Input.isRepeated("pagedown")) this._setYear(this._year + leap, true);
            else if (Input.isRepeated("pageup")) this._setYear(this._year - leap, true);
            else if (Input.isRepeated("tab")) this._stepSelection(1);
            else if (Input.isTriggered("shift")) {
                this._setMode(MODES[(MODES.indexOf(this._mode) + 1) % MODES.length]);
            } else if (Input.isTriggered("ok")) {
                if (this._selected) { SoundManager.playOk(); this._centreOn(this._selected); }
            } else if (Input.isTriggered("cancel")) {
                SoundManager.playCancel();
                this.popScene();
            }
        }

        // The map is fitted after the first layout pass, when the frame finally
        // has a width to fit the world into.
        start() {
            super.start();
            this._resetView();
            this._applyEra();
            this._paint();
        }

        terminate() {
            if (this._onResize) {
                window.removeEventListener("resize", this._onResize);
                this._onResize = null;
            }
            if (this._el) { this._el.remove(); this._el = null; }
            this._dom = null;
            this._countryNodes = null;
            this._labelNodes = null;
            super.terminate();
        }
    }

    // ── entry points ────────────────────────────────────────────────────────

    window.Scene_WorldAtlas = Scene_WorldAtlas;
    window.WorldAtlas = {
        open() {
            if (!atlasData()) {
                if (window.ParchmentToast) window.ParchmentToast.show(T("Atlas.noData"));
                else SoundManager.playBuzzer();
                return false;
            }
            SceneManager.push(Scene_WorldAtlas);
            return true;
        },
        isAvailable() { return !!atlasData(); },
    };

    PluginManager.registerCommand(PLUGIN, "openAtlas", () => { window.WorldAtlas.open(); });
})();
